package com.dunesrelics.client.model;

import com.dunesrelics.DunesRelics;
import com.dunesrelics.entity.volcanic.CinderWraith;
import net.minecraft.client.model.HierarchicalModel;
import net.minecraft.client.model.geom.ModelLayerLocation;
import net.minecraft.client.model.geom.ModelPart;
import net.minecraft.client.model.geom.PartPose;
import net.minecraft.client.model.geom.builders.CubeListBuilder;
import net.minecraft.client.model.geom.builders.LayerDefinition;
import net.minecraft.client.model.geom.builders.MeshDefinition;
import net.minecraft.client.model.geom.builders.PartDefinition;
import net.minecraft.util.Mth;

/**
 * Cinder wraith: a hooded spirit of drifting ash with ember eyes.
 * <p>Generated by tools/entity_models.py together with its texture; edit the script, not this file.
 */
@SuppressWarnings("unused")
public class CinderWraithModel<T extends CinderWraith> extends HierarchicalModel<T> {
    public static final ModelLayerLocation LAYER_LOCATION = new ModelLayerLocation(DunesRelics.id("cinder_wraith"), "main");

    private final ModelPart root;
    private final ModelPart head;
    private final ModelPart body;
    private final ModelPart robe;
    private final ModelPart tail;
    private final ModelPart rightArm;
    private final ModelPart leftArm;

    public CinderWraithModel(ModelPart root) {
        super(net.minecraft.client.renderer.RenderType::entityTranslucent);
        this.root = root;
        this.head = root.getChild("head");
        this.body = root.getChild("body");
        this.robe = this.body.getChild("robe");
        this.tail = this.robe.getChild("tail");
        this.rightArm = root.getChild("right_arm");
        this.leftArm = root.getChild("left_arm");
    }

    public static LayerDefinition createBodyLayer() {
        MeshDefinition mesh = new MeshDefinition();
        PartDefinition root = mesh.getRoot();
        PartDefinition head = root.addOrReplaceChild("head", CubeListBuilder.create().texOffs(0, 0).addBox(-3.5F, -7.0F, -3.5F, 7.0F, 7.0F, 7.0F),
                PartPose.offsetAndRotation(0.0F, 4.0F, 0.0F, 0.0F, 0.0F, 0.0F));
        PartDefinition body = root.addOrReplaceChild("body", CubeListBuilder.create().texOffs(28, 0).addBox(-3.0F, 0.0F, -2.0F, 6.0F, 8.0F, 4.0F),
                PartPose.offsetAndRotation(0.0F, 4.0F, 0.0F, 0.0F, 0.0F, 0.0F));
        PartDefinition robe = body.addOrReplaceChild("robe", CubeListBuilder.create().texOffs(0, 14).addBox(-2.5F, 0.0F, -1.5F, 5.0F, 5.0F, 3.0F),
                PartPose.offsetAndRotation(0.0F, 8.0F, 0.0F, 0.0F, 0.0F, 0.0F));
        PartDefinition tail = robe.addOrReplaceChild("tail", CubeListBuilder.create().texOffs(16, 14).addBox(-1.5F, 0.0F, -1.0F, 3.0F, 4.0F, 2.0F),
                PartPose.offsetAndRotation(0.0F, 5.0F, 0.0F, 0.0F, 0.0F, 0.0F));
        PartDefinition rightArm = root.addOrReplaceChild("right_arm", CubeListBuilder.create().texOffs(48, 0).addBox(-2.0F, 0.0F, -1.0F, 2.0F, 7.0F, 2.0F),
                PartPose.offsetAndRotation(-3.0F, 5.0F, 0.0F, 0.0F, 0.0F, 0.0F));
        PartDefinition leftArm = root.addOrReplaceChild("left_arm", CubeListBuilder.create().texOffs(48, 0).mirror().addBox(0.0F, 0.0F, -1.0F, 2.0F, 7.0F, 2.0F).mirror(false),
                PartPose.offsetAndRotation(3.0F, 5.0F, 0.0F, 0.0F, 0.0F, 0.0F));
        return LayerDefinition.create(mesh, 64, 32);
    }

    @Override
    public ModelPart root() {
        return this.root;
    }

    @Override
    public void setupAnim(T entity, float limbSwing, float limbSwingAmount, float ageInTicks, float netHeadYaw, float headPitch) {
        this.root().getAllParts().forEach(ModelPart::resetPose);
        this.head.yRot = netHeadYaw * Mth.DEG_TO_RAD;
        this.head.xRot = headPitch * Mth.DEG_TO_RAD;
        float bob = Mth.sin(ageInTicks * 0.1F);
        this.head.y += bob * 0.6F;
        this.body.y += bob * 0.6F;
        this.rightArm.y += bob * 0.6F;
        this.leftArm.y += bob * 0.6F;
        this.robe.xRot = 0.15F + Mth.sin(ageInTicks * 0.13F) * 0.1F;
        this.tail.xRot = 0.25F + Mth.sin(ageInTicks * 0.13F - 0.6F) * 0.2F;
        this.robe.zRot = Mth.sin(ageInTicks * 0.07F) * 0.06F;
        if (entity.isAggressive()) {
            // Reaching out with both arms.
            this.rightArm.xRot = -1.4F + Mth.sin(ageInTicks * 0.3F) * 0.1F;
            this.leftArm.xRot = -1.4F - Mth.sin(ageInTicks * 0.3F) * 0.1F;
        } else {
            this.rightArm.zRot = 0.15F + bob * 0.05F;
            this.leftArm.zRot = -0.15F - bob * 0.05F;
        }
    }
}
