package com.dunesrelics.client.model;

import com.dunesrelics.DunesRelics;
import com.dunesrelics.entity.volcanic.LavaCrab;
import net.minecraft.client.model.HierarchicalModel;
import net.minecraft.client.model.geom.ModelLayerLocation;
import net.minecraft.client.model.geom.ModelPart;
import net.minecraft.client.model.geom.PartPose;
import net.minecraft.client.model.geom.builders.CubeListBuilder;
import net.minecraft.client.model.geom.builders.LayerDefinition;
import net.minecraft.client.model.geom.builders.MeshDefinition;
import net.minecraft.client.model.geom.builders.PartDefinition;
import net.minecraft.util.Mth;

/**
 * Lava crab: a basalt-shelled crab with glowing seams that scuttles sideways.
 * <p>Generated by tools/entity_models.py together with its texture; edit the script, not this file.
 */
@SuppressWarnings("unused")
public class LavaCrabModel<T extends LavaCrab> extends HierarchicalModel<T> {
    public static final ModelLayerLocation LAYER_LOCATION = new ModelLayerLocation(DunesRelics.id("lava_crab"), "main");

    private final ModelPart root;
    private final ModelPart crab;
    private final ModelPart body;
    private final ModelPart rightEye;
    private final ModelPart leftEye;
    private final ModelPart rightClaw;
    private final ModelPart leftClaw;
    private final ModelPart rightFrontLeg;
    private final ModelPart leftFrontLeg;
    private final ModelPart rightMiddleLeg;
    private final ModelPart leftMiddleLeg;
    private final ModelPart rightHindLeg;
    private final ModelPart leftHindLeg;

    public LavaCrabModel(ModelPart root) {
        
        this.root = root;
        this.crab = root.getChild("crab");
        this.body = this.crab.getChild("body");
        this.rightEye = this.body.getChild("right_eye");
        this.leftEye = this.body.getChild("left_eye");
        this.rightClaw = this.body.getChild("right_claw");
        this.leftClaw = this.body.getChild("left_claw");
        this.rightFrontLeg = this.body.getChild("right_front_leg");
        this.leftFrontLeg = this.body.getChild("left_front_leg");
        this.rightMiddleLeg = this.body.getChild("right_middle_leg");
        this.leftMiddleLeg = this.body.getChild("left_middle_leg");
        this.rightHindLeg = this.body.getChild("right_hind_leg");
        this.leftHindLeg = this.body.getChild("left_hind_leg");
    }

    public static LayerDefinition createBodyLayer() {
        MeshDefinition mesh = new MeshDefinition();
        PartDefinition root = mesh.getRoot();
        PartDefinition crab = root.addOrReplaceChild("crab", CubeListBuilder.create(),
                PartPose.offsetAndRotation(0.0F, 24.0F, 0.0F, 0.0F, 1.5708F, 0.0F));
        PartDefinition body = crab.addOrReplaceChild("body", CubeListBuilder.create().texOffs(0, 0).addBox(-4.0F, -2.0F, -3.0F, 8.0F, 3.0F, 6.0F),
                PartPose.offsetAndRotation(0.0F, -4.0F, 0.0F, 0.0F, 0.0F, 0.0F));
        PartDefinition rightEye = body.addOrReplaceChild("right_eye", CubeListBuilder.create().texOffs(28, 0).addBox(-0.5F, -2.0F, -0.5F, 1.0F, 2.0F, 1.0F),
                PartPose.offsetAndRotation(-1.5F, -2.0F, -2.5F, 0.0F, 0.0F, 0.0F));
        PartDefinition leftEye = body.addOrReplaceChild("left_eye", CubeListBuilder.create().texOffs(28, 0).addBox(-0.5F, -2.0F, -0.5F, 1.0F, 2.0F, 1.0F),
                PartPose.offsetAndRotation(1.5F, -2.0F, -2.5F, 0.0F, 0.0F, 0.0F));
        PartDefinition rightClaw = body.addOrReplaceChild("right_claw", CubeListBuilder.create().texOffs(32, 0).addBox(-1.5F, -1.5F, -3.0F, 3.0F, 3.0F, 3.0F),
                PartPose.offsetAndRotation(-3.5F, 0.0F, -3.0F, 0.0F, 0.4F, 0.0F));
        PartDefinition leftClaw = body.addOrReplaceChild("left_claw", CubeListBuilder.create().texOffs(32, 0).mirror().addBox(-1.5F, -1.5F, -3.0F, 3.0F, 3.0F, 3.0F).mirror(false),
                PartPose.offsetAndRotation(3.5F, 0.0F, -3.0F, 0.0F, -0.4F, 0.0F));
        PartDefinition rightFrontLeg = body.addOrReplaceChild("right_front_leg", CubeListBuilder.create().texOffs(0, 9).addBox(-4.0F, 0.0F, -0.5F, 4.0F, 1.0F, 1.0F),
                PartPose.offsetAndRotation(-4.0F, 0.5F, -1.5F, 0.0F, 0.0F, -0.7F));
        PartDefinition leftFrontLeg = body.addOrReplaceChild("left_front_leg", CubeListBuilder.create().texOffs(0, 9).mirror().addBox(0.0F, 0.0F, -0.5F, 4.0F, 1.0F, 1.0F).mirror(false),
                PartPose.offsetAndRotation(4.0F, 0.5F, -1.5F, 0.0F, 0.0F, 0.7F));
        PartDefinition rightMiddleLeg = body.addOrReplaceChild("right_middle_leg", CubeListBuilder.create().texOffs(0, 9).addBox(-4.0F, 0.0F, -0.5F, 4.0F, 1.0F, 1.0F),
                PartPose.offsetAndRotation(-4.0F, 0.5F, 0.5F, 0.0F, 0.0F, -0.7F));
        PartDefinition leftMiddleLeg = body.addOrReplaceChild("left_middle_leg", CubeListBuilder.create().texOffs(0, 9).mirror().addBox(0.0F, 0.0F, -0.5F, 4.0F, 1.0F, 1.0F).mirror(false),
                PartPose.offsetAndRotation(4.0F, 0.5F, 0.5F, 0.0F, 0.0F, 0.7F));
        PartDefinition rightHindLeg = body.addOrReplaceChild("right_hind_leg", CubeListBuilder.create().texOffs(0, 9).addBox(-4.0F, 0.0F, -0.5F, 4.0F, 1.0F, 1.0F),
                PartPose.offsetAndRotation(-4.0F, 0.5F, 2.5F, 0.0F, 0.0F, -0.7F));
        PartDefinition leftHindLeg = body.addOrReplaceChild("left_hind_leg", CubeListBuilder.create().texOffs(0, 9).mirror().addBox(0.0F, 0.0F, -0.5F, 4.0F, 1.0F, 1.0F).mirror(false),
                PartPose.offsetAndRotation(4.0F, 0.5F, 2.5F, 0.0F, 0.0F, 0.7F));
        return LayerDefinition.create(mesh, 64, 32);
    }

    @Override
    public ModelPart root() {
        return this.root;
    }

    @Override
    public void setupAnim(T entity, float limbSwing, float limbSwingAmount, float ageInTicks, float netHeadYaw, float headPitch) {
        this.root().getAllParts().forEach(ModelPart::resetPose);
        // The whole crab is turned sideways, so walking forward is a scuttle.
        float walk = limbSwing * 1.6F;
        float a = Mth.cos(walk) * 0.5F * limbSwingAmount;
        float b = Mth.cos(walk + Mth.PI) * 0.5F * limbSwingAmount;
        this.rightFrontLeg.zRot += a;
        this.rightMiddleLeg.zRot += b;
        this.rightHindLeg.zRot += a;
        this.leftFrontLeg.zRot += b;
        this.leftMiddleLeg.zRot += a;
        this.leftHindLeg.zRot += b;
        this.body.y += Math.abs(Mth.sin(walk)) * 0.3F * limbSwingAmount;
        float snap = Mth.sin(this.attackTime * Mth.PI) * 0.6F + Mth.sin(ageInTicks * 0.1F) * 0.05F;
        this.rightClaw.yRot -= snap;
        this.leftClaw.yRot += snap;
        this.rightClaw.xRot = -snap * 0.5F;
        this.leftClaw.xRot = -snap * 0.5F;
        if (entity.isDancing()) {
            // Claws in the air!
            this.rightClaw.xRot = -1.2F + Mth.sin(ageInTicks * 0.8F) * 0.4F;
            this.leftClaw.xRot = -1.2F - Mth.sin(ageInTicks * 0.8F) * 0.4F;
            this.body.y += Mth.sin(ageInTicks * 0.8F) * 0.5F;
            this.body.zRot = Mth.sin(ageInTicks * 0.4F) * 0.15F;
        }
    }
}
