package com.dunesrelics.client.model;

import com.dunesrelics.DunesRelics;
import com.dunesrelics.entity.volcanic.Magmaling;
import net.minecraft.client.model.HierarchicalModel;
import net.minecraft.client.model.geom.ModelLayerLocation;
import net.minecraft.client.model.geom.ModelPart;
import net.minecraft.client.model.geom.PartPose;
import net.minecraft.client.model.geom.builders.CubeListBuilder;
import net.minecraft.client.model.geom.builders.LayerDefinition;
import net.minecraft.client.model.geom.builders.MeshDefinition;
import net.minecraft.client.model.geom.builders.PartDefinition;
import net.minecraft.util.Mth;

/**
 * Magmaling: a small walking lump of magma with a big glowing head.
 * <p>Generated by tools/entity_models.py together with its texture; edit the script, not this file.
 */
@SuppressWarnings("unused")
public class MagmalingModel<T extends Magmaling> extends HierarchicalModel<T> {
    public static final ModelLayerLocation LAYER_LOCATION = new ModelLayerLocation(DunesRelics.id("magmaling"), "main");

    private final ModelPart root;
    private final ModelPart body;
    private final ModelPart head;
    private final ModelPart rightArm;
    private final ModelPart leftArm;
    private final ModelPart rightLeg;
    private final ModelPart leftLeg;

    public MagmalingModel(ModelPart root) {
        
        this.root = root;
        this.body = root.getChild("body");
        this.head = root.getChild("head");
        this.rightArm = root.getChild("right_arm");
        this.leftArm = root.getChild("left_arm");
        this.rightLeg = root.getChild("right_leg");
        this.leftLeg = root.getChild("left_leg");
    }

    public static LayerDefinition createBodyLayer() {
        MeshDefinition mesh = new MeshDefinition();
        PartDefinition root = mesh.getRoot();
        PartDefinition body = root.addOrReplaceChild("body", CubeListBuilder.create().texOffs(28, 0).addBox(-3.0F, 0.0F, -2.0F, 6.0F, 6.0F, 4.0F),
                PartPose.offsetAndRotation(0.0F, 13.0F, 0.0F, 0.0F, 0.0F, 0.0F));
        PartDefinition head = root.addOrReplaceChild("head", CubeListBuilder.create().texOffs(0, 0).addBox(-3.5F, -7.0F, -3.5F, 7.0F, 7.0F, 7.0F),
                PartPose.offsetAndRotation(0.0F, 13.0F, 0.0F, 0.0F, 0.0F, 0.0F));
        PartDefinition rightArm = root.addOrReplaceChild("right_arm", CubeListBuilder.create().texOffs(48, 0).addBox(-2.0F, -1.0F, -1.0F, 2.0F, 6.0F, 2.0F),
                PartPose.offsetAndRotation(-3.0F, 14.0F, 0.0F, 0.0F, 0.0F, 0.0F));
        PartDefinition leftArm = root.addOrReplaceChild("left_arm", CubeListBuilder.create().texOffs(48, 0).mirror().addBox(0.0F, -1.0F, -1.0F, 2.0F, 6.0F, 2.0F).mirror(false),
                PartPose.offsetAndRotation(3.0F, 14.0F, 0.0F, 0.0F, 0.0F, 0.0F));
        PartDefinition rightLeg = root.addOrReplaceChild("right_leg", CubeListBuilder.create().texOffs(0, 14).addBox(-1.0F, 0.0F, -1.0F, 2.0F, 5.0F, 2.0F),
                PartPose.offsetAndRotation(-1.5F, 19.0F, 0.0F, 0.0F, 0.0F, 0.0F));
        PartDefinition leftLeg = root.addOrReplaceChild("left_leg", CubeListBuilder.create().texOffs(0, 14).mirror().addBox(-1.0F, 0.0F, -1.0F, 2.0F, 5.0F, 2.0F).mirror(false),
                PartPose.offsetAndRotation(1.5F, 19.0F, 0.0F, 0.0F, 0.0F, 0.0F));
        return LayerDefinition.create(mesh, 64, 32);
    }

    @Override
    public ModelPart root() {
        return this.root;
    }

    @Override
    public void setupAnim(T entity, float limbSwing, float limbSwingAmount, float ageInTicks, float netHeadYaw, float headPitch) {
        this.root().getAllParts().forEach(ModelPart::resetPose);
        this.head.yRot = netHeadYaw * Mth.DEG_TO_RAD;
        this.head.xRot = headPitch * Mth.DEG_TO_RAD;
        float walk = limbSwing * 0.6662F;
        this.rightLeg.xRot = Mth.cos(walk) * 1.2F * limbSwingAmount;
        this.leftLeg.xRot = -Mth.cos(walk) * 1.2F * limbSwingAmount;
        this.rightArm.xRot = -Mth.cos(walk) * 0.8F * limbSwingAmount;
        this.leftArm.xRot = Mth.cos(walk) * 0.8F * limbSwingAmount;
        this.head.y += Mth.sin(ageInTicks * 0.15F) * 0.4F;
        this.rightArm.zRot = 0.1F + Mth.sin(ageInTicks * 0.1F) * 0.05F;
        this.leftArm.zRot = -0.1F - Mth.sin(ageInTicks * 0.1F) * 0.05F;
        if (entity.isAggressive()) {
            this.rightArm.xRot = -1.9F + Mth.sin(ageInTicks * 0.3F) * 0.2F;
        }
    }
}
