package com.dunesrelics.client.model;

import com.dunesrelics.DunesRelics;
import com.dunesrelics.entity.volcanic.MagmaTitan;
import net.minecraft.client.model.HierarchicalModel;
import net.minecraft.client.model.geom.ModelLayerLocation;
import net.minecraft.client.model.geom.ModelPart;
import net.minecraft.client.model.geom.PartPose;
import net.minecraft.client.model.geom.builders.CubeListBuilder;
import net.minecraft.client.model.geom.builders.LayerDefinition;
import net.minecraft.client.model.geom.builders.MeshDefinition;
import net.minecraft.client.model.geom.builders.PartDefinition;
import net.minecraft.util.Mth;

/**
 * Magma Titan: a colossus of basalt with glowing magma veins, a burning core and enormous fists.
 * <p>Generated by tools/entity_models.py together with its texture; edit the script, not this file.
 */
@SuppressWarnings("unused")
public class MagmaTitanModel<T extends MagmaTitan> extends HierarchicalModel<T> {
    public static final ModelLayerLocation LAYER_LOCATION = new ModelLayerLocation(DunesRelics.id("magma_titan"), "main");

    private final ModelPart root;
    private final ModelPart body;
    private final ModelPart core;
    private final ModelPart head;
    private final ModelPart rightRock;
    private final ModelPart leftRock;
    private final ModelPart rightArm;
    private final ModelPart rightFist;
    private final ModelPart leftArm;
    private final ModelPart leftFist;
    private final ModelPart rightLeg;
    private final ModelPart leftLeg;

    public MagmaTitanModel(ModelPart root) {
        
        this.root = root;
        this.body = root.getChild("body");
        this.core = this.body.getChild("core");
        this.head = this.body.getChild("head");
        this.rightRock = this.body.getChild("right_rock");
        this.leftRock = this.body.getChild("left_rock");
        this.rightArm = root.getChild("right_arm");
        this.rightFist = this.rightArm.getChild("right_fist");
        this.leftArm = root.getChild("left_arm");
        this.leftFist = this.leftArm.getChild("left_fist");
        this.rightLeg = root.getChild("right_leg");
        this.leftLeg = root.getChild("left_leg");
    }

    public static LayerDefinition createBodyLayer() {
        MeshDefinition mesh = new MeshDefinition();
        PartDefinition root = mesh.getRoot();
        PartDefinition body = root.addOrReplaceChild("body", CubeListBuilder.create().texOffs(0, 0).addBox(-10.0F, -20.0F, -6.0F, 20.0F, 20.0F, 12.0F),
                PartPose.offsetAndRotation(0.0F, 6.0F, 0.0F, 0.0F, 0.0F, 0.0F));
        PartDefinition core = body.addOrReplaceChild("core", CubeListBuilder.create().texOffs(96, 20).addBox(-3.0F, -3.0F, -1.0F, 6.0F, 6.0F, 1.0F),
                PartPose.offsetAndRotation(0.0F, -12.0F, -6.0F, 0.0F, 0.0F, 0.0F));
        PartDefinition head = body.addOrReplaceChild("head", CubeListBuilder.create().texOffs(64, 0).addBox(-4.0F, -7.0F, -4.0F, 8.0F, 7.0F, 8.0F),
                PartPose.offsetAndRotation(0.0F, -20.0F, -2.0F, 0.0F, 0.0F, 0.0F));
        PartDefinition rightRock = body.addOrReplaceChild("right_rock", CubeListBuilder.create().texOffs(96, 0).addBox(-2.5F, -4.0F, -3.0F, 5.0F, 4.0F, 6.0F),
                PartPose.offsetAndRotation(-7.0F, -20.0F, 1.0F, 0.2F, 0.0F, -0.3F));
        PartDefinition leftRock = body.addOrReplaceChild("left_rock", CubeListBuilder.create().texOffs(96, 10).addBox(-2.0F, -3.0F, -2.0F, 4.0F, 3.0F, 4.0F),
                PartPose.offsetAndRotation(7.0F, -20.0F, 2.0F, -0.2F, 0.0F, 0.35F));
        PartDefinition rightArm = root.addOrReplaceChild("right_arm", CubeListBuilder.create().texOffs(0, 32).addBox(-7.0F, -3.0F, -4.0F, 7.0F, 22.0F, 8.0F),
                PartPose.offsetAndRotation(-12.0F, -11.0F, 0.0F, 0.0F, 0.0F, 0.0F));
        PartDefinition rightFist = rightArm.addOrReplaceChild("right_fist", CubeListBuilder.create().texOffs(60, 32).addBox(-4.5F, 0.0F, -4.5F, 9.0F, 8.0F, 9.0F),
                PartPose.offsetAndRotation(-3.5F, 19.0F, 0.0F, 0.0F, 0.0F, 0.0F));
        PartDefinition leftArm = root.addOrReplaceChild("left_arm", CubeListBuilder.create().texOffs(30, 32).mirror().addBox(0.0F, -3.0F, -4.0F, 7.0F, 22.0F, 8.0F).mirror(false),
                PartPose.offsetAndRotation(12.0F, -11.0F, 0.0F, 0.0F, 0.0F, 0.0F));
        PartDefinition leftFist = leftArm.addOrReplaceChild("left_fist", CubeListBuilder.create().texOffs(60, 32).mirror().addBox(-4.5F, 0.0F, -4.5F, 9.0F, 8.0F, 9.0F).mirror(false),
                PartPose.offsetAndRotation(3.5F, 19.0F, 0.0F, 0.0F, 0.0F, 0.0F));
        PartDefinition rightLeg = root.addOrReplaceChild("right_leg", CubeListBuilder.create().texOffs(0, 64).addBox(-3.5F, 0.0F, -3.5F, 7.0F, 18.0F, 7.0F),
                PartPose.offsetAndRotation(-5.0F, 6.0F, 0.0F, 0.0F, 0.0F, 0.0F));
        PartDefinition leftLeg = root.addOrReplaceChild("left_leg", CubeListBuilder.create().texOffs(28, 64).mirror().addBox(-3.5F, 0.0F, -3.5F, 7.0F, 18.0F, 7.0F).mirror(false),
                PartPose.offsetAndRotation(5.0F, 6.0F, 0.0F, 0.0F, 0.0F, 0.0F));
        return LayerDefinition.create(mesh, 128, 128);
    }

    @Override
    public ModelPart root() {
        return this.root;
    }

    @Override
    public void setupAnim(T entity, float limbSwing, float limbSwingAmount, float ageInTicks, float netHeadYaw, float headPitch) {
        this.root().getAllParts().forEach(ModelPart::resetPose);
        this.head.yRot = netHeadYaw * Mth.DEG_TO_RAD * 0.6F;
        this.head.xRot = headPitch * Mth.DEG_TO_RAD * 0.5F;

        float walk = limbSwing * 0.5F;
        this.rightLeg.xRot = Mth.cos(walk) * 0.9F * limbSwingAmount;
        this.leftLeg.xRot = -Mth.cos(walk) * 0.9F * limbSwingAmount;
        this.rightArm.xRot = -Mth.cos(walk) * 0.5F * limbSwingAmount;
        this.leftArm.xRot = Mth.cos(walk) * 0.5F * limbSwingAmount;
        this.body.zRot = Mth.cos(walk) * 0.04F * limbSwingAmount;
        this.body.xRot = 0.08F + Mth.sin(ageInTicks * 0.05F) * 0.02F;
        this.core.xScale = this.core.yScale = 1.0F + Mth.sin(ageInTicks * 0.2F) * 0.08F;

        // Punch with the right fist.
        float punch = Mth.sin(this.attackTime * Mth.PI);
        this.rightArm.xRot -= punch * 1.6F;

        // Ground slam: both fists raised overhead, then brought down.
        float partialTick = ageInTicks - entity.tickCount;
        int slam = entity.getSlamAnim();
        if (slam > 0) {
            float progress = 1.0F - (slam - partialTick) / com.dunesrelics.entity.volcanic.MagmaTitan.SLAM_DURATION;
            float lift = progress < 0.5F ? progress * 2.0F : 1.0F - (progress - 0.5F) * 2.0F;
            this.rightArm.xRot = -2.8F * lift;
            this.leftArm.xRot = -2.8F * lift;
            this.body.xRot = -0.25F * lift + 0.3F * (1.0F - lift) * (progress > 0.5F ? 1.0F : 0.0F);
        }
    }
}
