package com.dunesrelics.client.model;

import com.dunesrelics.DunesRelics;
import com.dunesrelics.entity.Meerkat;
import net.minecraft.client.model.HierarchicalModel;
import net.minecraft.client.model.geom.ModelLayerLocation;
import net.minecraft.client.model.geom.ModelPart;
import net.minecraft.client.model.geom.PartPose;
import net.minecraft.client.model.geom.builders.CubeListBuilder;
import net.minecraft.client.model.geom.builders.LayerDefinition;
import net.minecraft.client.model.geom.builders.MeshDefinition;
import net.minecraft.client.model.geom.builders.PartDefinition;
import net.minecraft.util.Mth;

/**
 * Meerkat: a slender, striped desert mongoose that rears up to keep a lookout.
 * <p>Generated by tools/entity_models.py together with its texture; edit the script, not this file.
 */
@SuppressWarnings("unused")
public class MeerkatModel<T extends Meerkat> extends HierarchicalModel<T> {
    public static final ModelLayerLocation LAYER_LOCATION = new ModelLayerLocation(DunesRelics.id("meerkat"), "main");

    private final ModelPart root;
    private final ModelPart body;
    private final ModelPart head;
    private final ModelPart rightEar;
    private final ModelPart leftEar;
    private final ModelPart rightFrontLeg;
    private final ModelPart leftFrontLeg;
    private final ModelPart tail;
    private final ModelPart rightHindLeg;
    private final ModelPart leftHindLeg;

    public MeerkatModel(ModelPart root) {
        
        this.root = root;
        this.body = root.getChild("body");
        this.head = this.body.getChild("head");
        this.rightEar = this.head.getChild("right_ear");
        this.leftEar = this.head.getChild("left_ear");
        this.rightFrontLeg = this.body.getChild("right_front_leg");
        this.leftFrontLeg = this.body.getChild("left_front_leg");
        this.tail = this.body.getChild("tail");
        this.rightHindLeg = root.getChild("right_hind_leg");
        this.leftHindLeg = root.getChild("left_hind_leg");
    }

    public static LayerDefinition createBodyLayer() {
        MeshDefinition mesh = new MeshDefinition();
        PartDefinition root = mesh.getRoot();
        PartDefinition body = root.addOrReplaceChild("body", CubeListBuilder.create().texOffs(0, 0).addBox(-2.0F, -2.5F, -8.0F, 4.0F, 4.0F, 8.0F),
                PartPose.offsetAndRotation(0.0F, 19.0F, 2.0F, 0.0F, 0.0F, 0.0F));
        PartDefinition head = body.addOrReplaceChild("head", CubeListBuilder.create().texOffs(24, 0).addBox(-2.0F, -2.5F, -3.0F, 4.0F, 4.0F, 3.0F).texOffs(38, 0).addBox(-1.0F, -0.5F, -5.0F, 2.0F, 2.0F, 2.0F),
                PartPose.offsetAndRotation(0.0F, -1.5F, -8.0F, 0.0F, 0.0F, 0.0F));
        PartDefinition rightEar = head.addOrReplaceChild("right_ear", CubeListBuilder.create().texOffs(46, 0).addBox(-0.5F, -0.5F, -0.5F, 1.0F, 1.0F, 1.0F),
                PartPose.offsetAndRotation(-2.0F, -2.0F, -1.0F, 0.0F, 0.0F, 0.0F));
        PartDefinition leftEar = head.addOrReplaceChild("left_ear", CubeListBuilder.create().texOffs(46, 0).mirror().addBox(-0.5F, -0.5F, -0.5F, 1.0F, 1.0F, 1.0F).mirror(false),
                PartPose.offsetAndRotation(2.0F, -2.0F, -1.0F, 0.0F, 0.0F, 0.0F));
        PartDefinition rightFrontLeg = body.addOrReplaceChild("right_front_leg", CubeListBuilder.create().texOffs(0, 12).addBox(-1.0F, 0.0F, -1.0F, 2.0F, 4.0F, 2.0F),
                PartPose.offsetAndRotation(-1.2F, 1.0F, -6.5F, 0.0F, 0.0F, 0.0F));
        PartDefinition leftFrontLeg = body.addOrReplaceChild("left_front_leg", CubeListBuilder.create().texOffs(0, 12).mirror().addBox(-1.0F, 0.0F, -1.0F, 2.0F, 4.0F, 2.0F).mirror(false),
                PartPose.offsetAndRotation(1.2F, 1.0F, -6.5F, 0.0F, 0.0F, 0.0F));
        PartDefinition tail = body.addOrReplaceChild("tail", CubeListBuilder.create().texOffs(8, 12).addBox(-0.5F, -0.5F, 0.0F, 1.0F, 1.0F, 8.0F),
                PartPose.offsetAndRotation(0.0F, -1.0F, 0.0F, -0.3F, 0.0F, 0.0F));
        PartDefinition rightHindLeg = root.addOrReplaceChild("right_hind_leg", CubeListBuilder.create().texOffs(0, 18).addBox(-1.0F, 0.0F, -1.0F, 2.0F, 4.0F, 2.0F),
                PartPose.offsetAndRotation(-1.5F, 20.0F, 1.0F, 0.0F, 0.0F, 0.0F));
        PartDefinition leftHindLeg = root.addOrReplaceChild("left_hind_leg", CubeListBuilder.create().texOffs(0, 18).mirror().addBox(-1.0F, 0.0F, -1.0F, 2.0F, 4.0F, 2.0F).mirror(false),
                PartPose.offsetAndRotation(1.5F, 20.0F, 1.0F, 0.0F, 0.0F, 0.0F));
        return LayerDefinition.create(mesh, 64, 32);
    }

    @Override
    public ModelPart root() {
        return this.root;
    }

    @Override
    public void setupAnim(T entity, float limbSwing, float limbSwingAmount, float ageInTicks, float netHeadYaw, float headPitch) {
        this.root().getAllParts().forEach(ModelPart::resetPose);
        float partialTick = ageInTicks - entity.tickCount;
        float stand = entity.getStandAnim(partialTick);

        // Walking.
        float walk = limbSwing * 0.6662F * 1.4F;
        float swing = Mth.cos(walk) * 1.2F * limbSwingAmount * (1.0F - stand);
        this.rightFrontLeg.xRot = swing;
        this.leftFrontLeg.xRot = -swing;
        this.rightHindLeg.xRot = -swing;
        this.leftHindLeg.xRot = swing;
        this.tail.xRot += Mth.cos(walk) * 0.15F * limbSwingAmount;
        this.tail.yRot = Mth.sin(ageInTicks * 0.08F) * 0.12F * (1.0F - stand);

        // Lookout pose: rear up on the hind legs, the tail propping the body up behind.
        this.body.xRot = -1.35F * stand;
        this.head.xRot = headPitch * Mth.DEG_TO_RAD + 1.35F * stand;
        this.head.yRot = netHeadYaw * Mth.DEG_TO_RAD;
        this.rightFrontLeg.xRot += 1.1F * stand;
        this.leftFrontLeg.xRot += 1.1F * stand;
        this.tail.xRot += 0.9F * stand;

        // Dancing to a jukebox: sway and bob the head.
        if (entity.isDancing()) {
            this.body.zRot = Mth.sin(ageInTicks * 0.4F) * 0.15F;
            this.head.zRot = Mth.sin(ageInTicks * 0.8F) * 0.3F;
            this.rightFrontLeg.zRot = Mth.sin(ageInTicks * 0.8F) * 0.5F;
            this.leftFrontLeg.zRot = -Mth.sin(ageInTicks * 0.8F) * 0.5F;
        }
    }
}
