package com.dunesrelics.client.model;

import com.dunesrelics.DunesRelics;
import com.dunesrelics.entity.volcanic.Salamander;
import net.minecraft.client.model.HierarchicalModel;
import net.minecraft.client.model.geom.ModelLayerLocation;
import net.minecraft.client.model.geom.ModelPart;
import net.minecraft.client.model.geom.PartPose;
import net.minecraft.client.model.geom.builders.CubeListBuilder;
import net.minecraft.client.model.geom.builders.LayerDefinition;
import net.minecraft.client.model.geom.builders.MeshDefinition;
import net.minecraft.client.model.geom.builders.PartDefinition;
import net.minecraft.util.Mth;

/**
 * Fire salamander: a black lizard with glowing ember spots and a long wriggling tail.
 * <p>Generated by tools/entity_models.py together with its texture; edit the script, not this file.
 */
@SuppressWarnings("unused")
public class SalamanderModel<T extends Salamander> extends HierarchicalModel<T> {
    public static final ModelLayerLocation LAYER_LOCATION = new ModelLayerLocation(DunesRelics.id("salamander"), "main");

    private final ModelPart root;
    private final ModelPart body;
    private final ModelPart head;
    private final ModelPart tail;
    private final ModelPart tailTip;
    private final ModelPart rightFrontLeg;
    private final ModelPart rightHindLeg;
    private final ModelPart leftFrontLeg;
    private final ModelPart leftHindLeg;

    public SalamanderModel(ModelPart root) {
        
        this.root = root;
        this.body = root.getChild("body");
        this.head = this.body.getChild("head");
        this.tail = this.body.getChild("tail");
        this.tailTip = this.tail.getChild("tail_tip");
        this.rightFrontLeg = root.getChild("right_front_leg");
        this.rightHindLeg = root.getChild("right_hind_leg");
        this.leftFrontLeg = root.getChild("left_front_leg");
        this.leftHindLeg = root.getChild("left_hind_leg");
    }

    public static LayerDefinition createBodyLayer() {
        MeshDefinition mesh = new MeshDefinition();
        PartDefinition root = mesh.getRoot();
        PartDefinition body = root.addOrReplaceChild("body", CubeListBuilder.create().texOffs(0, 0).addBox(-2.5F, -1.5F, -5.0F, 5.0F, 3.0F, 10.0F),
                PartPose.offsetAndRotation(0.0F, 21.0F, 0.0F, 0.0F, 0.0F, 0.0F));
        PartDefinition head = body.addOrReplaceChild("head", CubeListBuilder.create().texOffs(30, 0).addBox(-2.5F, -1.5F, -4.0F, 5.0F, 3.0F, 4.0F),
                PartPose.offsetAndRotation(0.0F, 0.0F, -5.0F, 0.0F, 0.0F, 0.0F));
        PartDefinition tail = body.addOrReplaceChild("tail", CubeListBuilder.create().texOffs(0, 13).addBox(-1.5F, -1.0F, 0.0F, 3.0F, 2.0F, 6.0F),
                PartPose.offsetAndRotation(0.0F, -0.5F, 5.0F, 0.0F, 0.0F, 0.0F));
        PartDefinition tailTip = tail.addOrReplaceChild("tail_tip", CubeListBuilder.create().texOffs(18, 13).addBox(-1.0F, -0.5F, 0.0F, 2.0F, 1.0F, 6.0F),
                PartPose.offsetAndRotation(0.0F, 0.0F, 6.0F, 0.0F, 0.0F, 0.0F));
        PartDefinition rightFrontLeg = root.addOrReplaceChild("right_front_leg", CubeListBuilder.create().texOffs(34, 13).addBox(-3.0F, -0.5F, -1.0F, 3.0F, 1.0F, 2.0F).texOffs(44, 13).addBox(-3.0F, 0.5F, -1.0F, 1.0F, 2.0F, 2.0F),
                PartPose.offsetAndRotation(-2.5F, 21.5F, -3.0F, 0.0F, 0.0F, 0.0F));
        PartDefinition rightHindLeg = root.addOrReplaceChild("right_hind_leg", CubeListBuilder.create().texOffs(34, 13).addBox(-3.0F, -0.5F, -1.0F, 3.0F, 1.0F, 2.0F).texOffs(44, 13).addBox(-3.0F, 0.5F, -1.0F, 1.0F, 2.0F, 2.0F),
                PartPose.offsetAndRotation(-2.5F, 21.5F, 3.0F, 0.0F, 0.0F, 0.0F));
        PartDefinition leftFrontLeg = root.addOrReplaceChild("left_front_leg", CubeListBuilder.create().texOffs(34, 13).mirror().addBox(0.0F, -0.5F, -1.0F, 3.0F, 1.0F, 2.0F).mirror(false).texOffs(44, 13).mirror().addBox(2.0F, 0.5F, -1.0F, 1.0F, 2.0F, 2.0F).mirror(false),
                PartPose.offsetAndRotation(2.5F, 21.5F, -3.0F, 0.0F, 0.0F, 0.0F));
        PartDefinition leftHindLeg = root.addOrReplaceChild("left_hind_leg", CubeListBuilder.create().texOffs(34, 13).mirror().addBox(0.0F, -0.5F, -1.0F, 3.0F, 1.0F, 2.0F).mirror(false).texOffs(44, 13).mirror().addBox(2.0F, 0.5F, -1.0F, 1.0F, 2.0F, 2.0F).mirror(false),
                PartPose.offsetAndRotation(2.5F, 21.5F, 3.0F, 0.0F, 0.0F, 0.0F));
        return LayerDefinition.create(mesh, 64, 32);
    }

    @Override
    public ModelPart root() {
        return this.root;
    }

    @Override
    public void setupAnim(T entity, float limbSwing, float limbSwingAmount, float ageInTicks, float netHeadYaw, float headPitch) {
        this.root().getAllParts().forEach(ModelPart::resetPose);
        this.head.yRot = netHeadYaw * Mth.DEG_TO_RAD * 0.5F;
        this.head.xRot = headPitch * Mth.DEG_TO_RAD * 0.3F;
        if (entity.isInSittingPose()) {
            // Lying flat, tail curled around.
            this.tail.yRot = 0.9F;
            this.tailTip.yRot = 1.2F;
            this.rightFrontLeg.yRot = -0.5F;
            this.leftFrontLeg.yRot = 0.5F;
            this.rightHindLeg.yRot = 0.5F;
            this.leftHindLeg.yRot = -0.5F;
            return;
        }
        // A lizard's gait: diagonal legs move together while the body and tail wriggle.
        float walk = limbSwing * 1.2F;
        float swing = Mth.cos(walk) * 0.8F * limbSwingAmount;
        this.rightFrontLeg.yRot = swing;
        this.leftHindLeg.yRot = swing;
        this.leftFrontLeg.yRot = swing;
        this.rightHindLeg.yRot = swing;
        this.body.yRot = Mth.sin(walk) * 0.12F * limbSwingAmount;
        this.tail.yRot = -Mth.sin(walk) * 0.35F * limbSwingAmount + Mth.sin(ageInTicks * 0.1F) * 0.1F;
        this.tailTip.yRot = -Mth.sin(walk - 0.8F) * 0.4F * limbSwingAmount + Mth.sin(ageInTicks * 0.1F - 0.5F) * 0.15F;
    }
}
