package com.dunesrelics.client.model;

import com.dunesrelics.DunesRelics;
import com.dunesrelics.entity.Scarab;
import net.minecraft.client.model.HierarchicalModel;
import net.minecraft.client.model.geom.ModelLayerLocation;
import net.minecraft.client.model.geom.ModelPart;
import net.minecraft.client.model.geom.PartPose;
import net.minecraft.client.model.geom.builders.CubeListBuilder;
import net.minecraft.client.model.geom.builders.LayerDefinition;
import net.minecraft.client.model.geom.builders.MeshDefinition;
import net.minecraft.client.model.geom.builders.PartDefinition;
import net.minecraft.util.Mth;

/**
 * Scarab: a lapis-blue beetle with a gilded shell seam and six scurrying legs.
 * <p>Generated by tools/entity_models.py together with its texture; edit the script, not this file.
 */
@SuppressWarnings("unused")
public class ScarabModel<T extends Scarab> extends HierarchicalModel<T> {
    public static final ModelLayerLocation LAYER_LOCATION = new ModelLayerLocation(DunesRelics.id("scarab"), "main");

    private final ModelPart root;
    private final ModelPart body;
    private final ModelPart head;
    private final ModelPart rightFrontLeg;
    private final ModelPart leftFrontLeg;
    private final ModelPart rightMiddleLeg;
    private final ModelPart leftMiddleLeg;
    private final ModelPart rightHindLeg;
    private final ModelPart leftHindLeg;

    public ScarabModel(ModelPart root) {
        
        this.root = root;
        this.body = root.getChild("body");
        this.head = root.getChild("head");
        this.rightFrontLeg = root.getChild("right_front_leg");
        this.leftFrontLeg = root.getChild("left_front_leg");
        this.rightMiddleLeg = root.getChild("right_middle_leg");
        this.leftMiddleLeg = root.getChild("left_middle_leg");
        this.rightHindLeg = root.getChild("right_hind_leg");
        this.leftHindLeg = root.getChild("left_hind_leg");
    }

    public static LayerDefinition createBodyLayer() {
        MeshDefinition mesh = new MeshDefinition();
        PartDefinition root = mesh.getRoot();
        PartDefinition body = root.addOrReplaceChild("body", CubeListBuilder.create().texOffs(0, 0).addBox(-2.5F, -1.5F, -3.0F, 5.0F, 3.0F, 6.0F),
                PartPose.offsetAndRotation(0.0F, 21.5F, 0.0F, 0.0F, 0.0F, 0.0F));
        PartDefinition head = root.addOrReplaceChild("head", CubeListBuilder.create().texOffs(0, 9).addBox(-1.5F, -1.0F, -2.0F, 3.0F, 2.0F, 2.0F).texOffs(10, 9).addBox(-1.0F, -0.5F, -3.0F, 2.0F, 1.0F, 1.0F),
                PartPose.offsetAndRotation(0.0F, 22.0F, -3.0F, 0.0F, 0.0F, 0.0F));
        PartDefinition rightFrontLeg = root.addOrReplaceChild("right_front_leg", CubeListBuilder.create().texOffs(16, 9).addBox(-3.0F, -0.5F, -0.5F, 3.0F, 1.0F, 1.0F),
                PartPose.offsetAndRotation(-2.5F, 22.5F, -2.0F, 0.0F, -0.5F, -0.5F));
        PartDefinition leftFrontLeg = root.addOrReplaceChild("left_front_leg", CubeListBuilder.create().texOffs(16, 9).mirror().addBox(0.0F, -0.5F, -0.5F, 3.0F, 1.0F, 1.0F).mirror(false),
                PartPose.offsetAndRotation(2.5F, 22.5F, -2.0F, 0.0F, 0.5F, 0.5F));
        PartDefinition rightMiddleLeg = root.addOrReplaceChild("right_middle_leg", CubeListBuilder.create().texOffs(16, 9).addBox(-3.0F, -0.5F, -0.5F, 3.0F, 1.0F, 1.0F),
                PartPose.offsetAndRotation(-2.5F, 22.5F, 0.0F, 0.0F, 0.0F, -0.5F));
        PartDefinition leftMiddleLeg = root.addOrReplaceChild("left_middle_leg", CubeListBuilder.create().texOffs(16, 9).mirror().addBox(0.0F, -0.5F, -0.5F, 3.0F, 1.0F, 1.0F).mirror(false),
                PartPose.offsetAndRotation(2.5F, 22.5F, 0.0F, 0.0F, -0.0F, 0.5F));
        PartDefinition rightHindLeg = root.addOrReplaceChild("right_hind_leg", CubeListBuilder.create().texOffs(16, 9).addBox(-3.0F, -0.5F, -0.5F, 3.0F, 1.0F, 1.0F),
                PartPose.offsetAndRotation(-2.5F, 22.5F, 2.0F, 0.0F, 0.5F, -0.5F));
        PartDefinition leftHindLeg = root.addOrReplaceChild("left_hind_leg", CubeListBuilder.create().texOffs(16, 9).mirror().addBox(0.0F, -0.5F, -0.5F, 3.0F, 1.0F, 1.0F).mirror(false),
                PartPose.offsetAndRotation(2.5F, 22.5F, 2.0F, 0.0F, -0.5F, 0.5F));
        return LayerDefinition.create(mesh, 32, 16);
    }

    @Override
    public ModelPart root() {
        return this.root;
    }

    @Override
    public void setupAnim(T entity, float limbSwing, float limbSwingAmount, float ageInTicks, float netHeadYaw, float headPitch) {
        this.root().getAllParts().forEach(ModelPart::resetPose);
        this.head.yRot = netHeadYaw * Mth.DEG_TO_RAD * 0.4F;
        float walk = limbSwing * 1.4F;
        float a = Mth.cos(walk) * 0.6F * limbSwingAmount;
        float b = Mth.cos(walk + Mth.PI) * 0.6F * limbSwingAmount;
        this.rightFrontLeg.yRot += a;
        this.leftMiddleLeg.yRot -= a;
        this.rightHindLeg.yRot += a;
        this.leftFrontLeg.yRot -= b;
        this.rightMiddleLeg.yRot += b;
        this.leftHindLeg.yRot -= b;
        this.body.zRot = Mth.sin(walk) * 0.05F * limbSwingAmount;
    }
}
