package com.dunesrelics.client.model;

import com.dunesrelics.DunesRelics;
import com.dunesrelics.entity.Scorpion;
import net.minecraft.client.model.HierarchicalModel;
import net.minecraft.client.model.geom.ModelLayerLocation;
import net.minecraft.client.model.geom.ModelPart;
import net.minecraft.client.model.geom.PartPose;
import net.minecraft.client.model.geom.builders.CubeListBuilder;
import net.minecraft.client.model.geom.builders.LayerDefinition;
import net.minecraft.client.model.geom.builders.MeshDefinition;
import net.minecraft.client.model.geom.builders.PartDefinition;
import net.minecraft.util.Mth;

/**
 * Scorpion: segmented body, two pincers, eight legs and a curled, striking tail.
 * <p>Generated by tools/entity_models.py together with its texture; edit the script, not this file.
 */
@SuppressWarnings("unused")
public class ScorpionModel<T extends Scorpion> extends HierarchicalModel<T> {
    public static final ModelLayerLocation LAYER_LOCATION = new ModelLayerLocation(DunesRelics.id("scorpion"), "main");

    private final ModelPart root;
    private final ModelPart body;
    private final ModelPart head;
    private final ModelPart rightArm;
    private final ModelPart rightClaw;
    private final ModelPart leftArm;
    private final ModelPart leftClaw;
    private final ModelPart tail1;
    private final ModelPart tail2;
    private final ModelPart tail3;
    private final ModelPart tail4;
    private final ModelPart stinger;
    private final ModelPart rightFrontLeg;
    private final ModelPart leftFrontLeg;
    private final ModelPart rightMiddleFrontLeg;
    private final ModelPart leftMiddleFrontLeg;
    private final ModelPart rightMiddleHindLeg;
    private final ModelPart leftMiddleHindLeg;
    private final ModelPart rightHindLeg;
    private final ModelPart leftHindLeg;

    public ScorpionModel(ModelPart root) {
        this.root = root;
        this.body = root.getChild("body");
        this.head = root.getChild("head");
        this.rightArm = root.getChild("right_arm");
        this.rightClaw = this.rightArm.getChild("right_claw");
        this.leftArm = root.getChild("left_arm");
        this.leftClaw = this.leftArm.getChild("left_claw");
        this.tail1 = root.getChild("tail1");
        this.tail2 = this.tail1.getChild("tail2");
        this.tail3 = this.tail2.getChild("tail3");
        this.tail4 = this.tail3.getChild("tail4");
        this.stinger = this.tail4.getChild("stinger");
        this.rightFrontLeg = root.getChild("right_front_leg");
        this.leftFrontLeg = root.getChild("left_front_leg");
        this.rightMiddleFrontLeg = root.getChild("right_middle_front_leg");
        this.leftMiddleFrontLeg = root.getChild("left_middle_front_leg");
        this.rightMiddleHindLeg = root.getChild("right_middle_hind_leg");
        this.leftMiddleHindLeg = root.getChild("left_middle_hind_leg");
        this.rightHindLeg = root.getChild("right_hind_leg");
        this.leftHindLeg = root.getChild("left_hind_leg");
    }

    public static LayerDefinition createBodyLayer() {
        MeshDefinition mesh = new MeshDefinition();
        PartDefinition root = mesh.getRoot();
        PartDefinition body = root.addOrReplaceChild("body", CubeListBuilder.create().texOffs(0, 0).addBox(-4.0F, -2.0F, -6.0F, 8.0F, 4.0F, 12.0F),
                PartPose.offsetAndRotation(0.0F, 19.0F, 0.0F, 0.0F, 0.0F, 0.0F));
        PartDefinition head = root.addOrReplaceChild("head", CubeListBuilder.create().texOffs(0, 16).addBox(-3.0F, -1.5F, -3.0F, 6.0F, 3.0F, 3.0F),
                PartPose.offsetAndRotation(0.0F, 19.5F, -6.0F, 0.0F, 0.0F, 0.0F));
        PartDefinition rightArm = root.addOrReplaceChild("right_arm", CubeListBuilder.create().texOffs(20, 16).addBox(-1.0F, -1.0F, -5.0F, 2.0F, 2.0F, 5.0F),
                PartPose.offsetAndRotation(-2.5F, 19.5F, -8.0F, 0.0F, 0.5F, 0.0F));
        PartDefinition rightClaw = rightArm.addOrReplaceChild("right_claw", CubeListBuilder.create().texOffs(34, 16).addBox(-2.0F, -1.5F, -4.0F, 4.0F, 3.0F, 4.0F),
                PartPose.offsetAndRotation(0.0F, 0.0F, -5.0F, 0.0F, 0.0F, 0.0F));
        PartDefinition leftArm = root.addOrReplaceChild("left_arm", CubeListBuilder.create().texOffs(20, 16).mirror().addBox(-1.0F, -1.0F, -5.0F, 2.0F, 2.0F, 5.0F).mirror(false),
                PartPose.offsetAndRotation(2.5F, 19.5F, -8.0F, 0.0F, -0.5F, 0.0F));
        PartDefinition leftClaw = leftArm.addOrReplaceChild("left_claw", CubeListBuilder.create().texOffs(34, 16).mirror().addBox(-2.0F, -1.5F, -4.0F, 4.0F, 3.0F, 4.0F).mirror(false),
                PartPose.offsetAndRotation(0.0F, 0.0F, -5.0F, 0.0F, 0.0F, 0.0F));
        PartDefinition tail1 = root.addOrReplaceChild("tail1", CubeListBuilder.create().texOffs(0, 24).addBox(-1.5F, -1.5F, 0.0F, 3.0F, 3.0F, 5.0F),
                PartPose.offsetAndRotation(0.0F, 18.0F, 6.0F, 0.9F, 0.0F, 0.0F));
        PartDefinition tail2 = tail1.addOrReplaceChild("tail2", CubeListBuilder.create().texOffs(16, 24).addBox(-1.5F, -1.5F, 0.0F, 3.0F, 3.0F, 5.0F),
                PartPose.offsetAndRotation(0.0F, 0.0F, 5.0F, 0.9F, 0.0F, 0.0F));
        PartDefinition tail3 = tail2.addOrReplaceChild("tail3", CubeListBuilder.create().texOffs(32, 24).addBox(-1.0F, -1.0F, 0.0F, 2.0F, 2.0F, 5.0F),
                PartPose.offsetAndRotation(0.0F, 0.0F, 5.0F, 0.8F, 0.0F, 0.0F));
        PartDefinition tail4 = tail3.addOrReplaceChild("tail4", CubeListBuilder.create().texOffs(46, 24).addBox(-1.0F, -1.0F, 0.0F, 2.0F, 2.0F, 4.0F),
                PartPose.offsetAndRotation(0.0F, 0.0F, 5.0F, 0.7F, 0.0F, 0.0F));
        PartDefinition stinger = tail4.addOrReplaceChild("stinger", CubeListBuilder.create().texOffs(0, 32).addBox(-1.0F, -1.0F, 0.0F, 2.0F, 2.0F, 2.0F).texOffs(8, 32).addBox(-0.5F, -0.5F, 2.0F, 1.0F, 1.0F, 2.0F),
                PartPose.offsetAndRotation(0.0F, 0.0F, 4.0F, 0.6F, 0.0F, 0.0F));
        PartDefinition rightFrontLeg = root.addOrReplaceChild("right_front_leg", CubeListBuilder.create().texOffs(16, 32).addBox(-9.0F, -1.0F, -1.0F, 9.0F, 2.0F, 2.0F),
                PartPose.offsetAndRotation(-4.0F, 19.5F, -3.5F, 0.0F, -0.6F, -0.55F));
        PartDefinition leftFrontLeg = root.addOrReplaceChild("left_front_leg", CubeListBuilder.create().texOffs(16, 32).mirror().addBox(0.0F, -1.0F, -1.0F, 9.0F, 2.0F, 2.0F).mirror(false),
                PartPose.offsetAndRotation(4.0F, 19.5F, -3.5F, 0.0F, 0.6F, 0.55F));
        PartDefinition rightMiddleFrontLeg = root.addOrReplaceChild("right_middle_front_leg", CubeListBuilder.create().texOffs(16, 32).addBox(-9.0F, -1.0F, -1.0F, 9.0F, 2.0F, 2.0F),
                PartPose.offsetAndRotation(-4.0F, 19.5F, -1.0F, 0.0F, -0.2F, -0.55F));
        PartDefinition leftMiddleFrontLeg = root.addOrReplaceChild("left_middle_front_leg", CubeListBuilder.create().texOffs(16, 32).mirror().addBox(0.0F, -1.0F, -1.0F, 9.0F, 2.0F, 2.0F).mirror(false),
                PartPose.offsetAndRotation(4.0F, 19.5F, -1.0F, 0.0F, 0.2F, 0.55F));
        PartDefinition rightMiddleHindLeg = root.addOrReplaceChild("right_middle_hind_leg", CubeListBuilder.create().texOffs(16, 32).addBox(-9.0F, -1.0F, -1.0F, 9.0F, 2.0F, 2.0F),
                PartPose.offsetAndRotation(-4.0F, 19.5F, 1.5F, 0.0F, 0.2F, -0.55F));
        PartDefinition leftMiddleHindLeg = root.addOrReplaceChild("left_middle_hind_leg", CubeListBuilder.create().texOffs(16, 32).mirror().addBox(0.0F, -1.0F, -1.0F, 9.0F, 2.0F, 2.0F).mirror(false),
                PartPose.offsetAndRotation(4.0F, 19.5F, 1.5F, 0.0F, -0.2F, 0.55F));
        PartDefinition rightHindLeg = root.addOrReplaceChild("right_hind_leg", CubeListBuilder.create().texOffs(16, 32).addBox(-9.0F, -1.0F, -1.0F, 9.0F, 2.0F, 2.0F),
                PartPose.offsetAndRotation(-4.0F, 19.5F, 4.0F, 0.0F, 0.6F, -0.55F));
        PartDefinition leftHindLeg = root.addOrReplaceChild("left_hind_leg", CubeListBuilder.create().texOffs(16, 32).mirror().addBox(0.0F, -1.0F, -1.0F, 9.0F, 2.0F, 2.0F).mirror(false),
                PartPose.offsetAndRotation(4.0F, 19.5F, 4.0F, 0.0F, -0.6F, 0.55F));
        return LayerDefinition.create(mesh, 64, 64);
    }

    @Override
    public ModelPart root() {
        return this.root;
    }

    @Override
    public void setupAnim(T entity, float limbSwing, float limbSwingAmount, float ageInTicks, float netHeadYaw, float headPitch) {
        this.root().getAllParts().forEach(ModelPart::resetPose);
        this.head.yRot = netHeadYaw * Mth.DEG_TO_RAD * 0.5F;
        this.head.xRot = headPitch * Mth.DEG_TO_RAD * 0.3F;

        float walk = limbSwing * 0.6662F * 2.0F;
        float swingFront = -(Mth.cos(walk) * 0.4F) * limbSwingAmount;
        float swingMidFront = -(Mth.cos(walk + Mth.PI) * 0.4F) * limbSwingAmount;
        float swingMidHind = -(Mth.cos(walk + Mth.HALF_PI) * 0.4F) * limbSwingAmount;
        float swingHind = -(Mth.cos(walk + Mth.PI * 1.5F) * 0.4F) * limbSwingAmount;
        float liftFront = Math.abs(Mth.sin(limbSwing * 0.6662F) * 0.4F) * limbSwingAmount;
        float liftMidFront = Math.abs(Mth.sin(limbSwing * 0.6662F + Mth.PI) * 0.4F) * limbSwingAmount;
        float liftMidHind = Math.abs(Mth.sin(limbSwing * 0.6662F + Mth.HALF_PI) * 0.4F) * limbSwingAmount;
        float liftHind = Math.abs(Mth.sin(limbSwing * 0.6662F + Mth.PI * 1.5F) * 0.4F) * limbSwingAmount;
        this.rightFrontLeg.yRot += swingFront;
        this.leftFrontLeg.yRot -= swingFront;
        this.rightMiddleFrontLeg.yRot += swingMidFront;
        this.leftMiddleFrontLeg.yRot -= swingMidFront;
        this.rightMiddleHindLeg.yRot += swingMidHind;
        this.leftMiddleHindLeg.yRot -= swingMidHind;
        this.rightHindLeg.yRot += swingHind;
        this.leftHindLeg.yRot -= swingHind;
        this.rightFrontLeg.zRot -= liftFront;
        this.leftFrontLeg.zRot += liftFront;
        this.rightMiddleFrontLeg.zRot -= liftMidFront;
        this.leftMiddleFrontLeg.zRot += liftMidFront;
        this.rightMiddleHindLeg.zRot -= liftMidHind;
        this.leftMiddleHindLeg.zRot += liftMidHind;
        this.rightHindLeg.zRot -= liftHind;
        this.leftHindLeg.zRot += liftHind;

        // The tail sways slowly and the pincers flex; attacks lash the tail forward and snap the claws.
        float sway = Mth.sin(ageInTicks * 0.06F);
        this.tail1.yRot = sway * 0.12F;
        this.tail2.xRot += Mth.sin(ageInTicks * 0.09F) * 0.05F;
        this.tail4.xRot += Mth.sin(ageInTicks * 0.09F + 1.0F) * 0.06F;
        float strike = Mth.sin(this.attackTime * Mth.PI);
        this.tail1.xRot -= strike * 0.25F;
        this.tail3.xRot += strike * 0.35F;
        this.stinger.xRot += strike * 0.5F;
        float pinch = Mth.sin(ageInTicks * 0.15F) * 0.08F + strike * 0.45F;
        this.rightArm.yRot -= pinch;
        this.leftArm.yRot += pinch;
        this.rightClaw.yRot += Mth.sin(ageInTicks * 0.2F) * 0.1F;
        this.leftClaw.yRot -= Mth.sin(ageInTicks * 0.2F) * 0.1F;
    }
}
