package com.dunesrelics.client.model;

import com.dunesrelics.DunesRelics;
import com.dunesrelics.entity.world.Shade;
import net.minecraft.client.model.HierarchicalModel;
import net.minecraft.client.model.geom.ModelLayerLocation;
import net.minecraft.client.model.geom.ModelPart;
import net.minecraft.client.model.geom.PartPose;
import net.minecraft.client.model.geom.builders.CubeListBuilder;
import net.minecraft.client.model.geom.builders.LayerDefinition;
import net.minecraft.client.model.geom.builders.MeshDefinition;
import net.minecraft.client.model.geom.builders.PartDefinition;
import net.minecraft.util.Mth;

/**
 * Shade: a tall, thin figure of darkness with two pale eyes.
 * <p>Generated by tools/entity_models.py together with its texture; edit the script, not this file.
 */
@SuppressWarnings("unused")
public class ShadeModel<T extends Shade> extends HierarchicalModel<T> {
    public static final ModelLayerLocation LAYER_LOCATION = new ModelLayerLocation(DunesRelics.id("shade"), "main");

    private final ModelPart root;
    private final ModelPart body;
    private final ModelPart head;
    private final ModelPart rightArm;
    private final ModelPart leftArm;
    private final ModelPart rightLeg;
    private final ModelPart leftLeg;

    public ShadeModel(ModelPart root) {
        
        this.root = root;
        this.body = root.getChild("body");
        this.head = root.getChild("head");
        this.rightArm = root.getChild("right_arm");
        this.leftArm = root.getChild("left_arm");
        this.rightLeg = root.getChild("right_leg");
        this.leftLeg = root.getChild("left_leg");
    }

    public static LayerDefinition createBodyLayer() {
        MeshDefinition mesh = new MeshDefinition();
        PartDefinition root = mesh.getRoot();
        PartDefinition body = root.addOrReplaceChild("body", CubeListBuilder.create().texOffs(0, 16).addBox(-3.0F, 0.0F, -1.5F, 6.0F, 14.0F, 3.0F),
                PartPose.offsetAndRotation(0.0F, -8.0F, 0.0F, 0.0F, 0.0F, 0.0F));
        PartDefinition head = root.addOrReplaceChild("head", CubeListBuilder.create().texOffs(0, 0).addBox(-3.0F, -8.0F, -3.0F, 6.0F, 8.0F, 6.0F),
                PartPose.offsetAndRotation(0.0F, -8.0F, 0.0F, 0.0F, 0.0F, 0.0F));
        PartDefinition rightArm = root.addOrReplaceChild("right_arm", CubeListBuilder.create().texOffs(24, 0).addBox(-1.5F, 0.0F, -1.0F, 2.0F, 20.0F, 2.0F),
                PartPose.offsetAndRotation(-4.0F, -7.0F, 0.0F, 0.0F, 0.0F, 0.0F));
        PartDefinition leftArm = root.addOrReplaceChild("left_arm", CubeListBuilder.create().texOffs(24, 0).mirror().addBox(-0.5F, 0.0F, -1.0F, 2.0F, 20.0F, 2.0F).mirror(false),
                PartPose.offsetAndRotation(4.0F, -7.0F, 0.0F, 0.0F, 0.0F, 0.0F));
        PartDefinition rightLeg = root.addOrReplaceChild("right_leg", CubeListBuilder.create().texOffs(32, 0).addBox(-1.0F, 0.0F, -1.0F, 2.0F, 18.0F, 2.0F),
                PartPose.offsetAndRotation(-1.5F, 6.0F, 0.0F, 0.0F, 0.0F, 0.0F));
        PartDefinition leftLeg = root.addOrReplaceChild("left_leg", CubeListBuilder.create().texOffs(32, 0).mirror().addBox(-1.0F, 0.0F, -1.0F, 2.0F, 18.0F, 2.0F).mirror(false),
                PartPose.offsetAndRotation(1.5F, 6.0F, 0.0F, 0.0F, 0.0F, 0.0F));
        return LayerDefinition.create(mesh, 64, 64);
    }

    @Override
    public ModelPart root() {
        return this.root;
    }

    @Override
    public void setupAnim(T entity, float limbSwing, float limbSwingAmount, float ageInTicks, float netHeadYaw, float headPitch) {
        this.root().getAllParts().forEach(ModelPart::resetPose);
        if (entity.isWatched()) {
            // Frozen mid-step the moment it is seen, head cocked to one side.
            this.head.zRot = 0.4F;
            this.head.xRot = -0.1F;
            this.rightArm.xRot = -0.25F;
            this.leftArm.xRot = -0.15F;
            this.rightArm.zRot = 0.08F;
            this.leftArm.zRot = -0.08F;
            return;
        }
        this.head.yRot = netHeadYaw * Mth.DEG_TO_RAD;
        this.head.xRot = headPitch * Mth.DEG_TO_RAD;
        this.head.zRot = Mth.sin(ageInTicks * 0.9F) * 0.03F;
        float swing = limbSwing * 0.5F;
        this.rightLeg.xRot = Mth.cos(swing) * 0.9F * limbSwingAmount;
        this.leftLeg.xRot = Mth.cos(swing + Mth.PI) * 0.9F * limbSwingAmount;
        this.rightArm.xRot = Mth.cos(swing + Mth.PI) * 0.35F * limbSwingAmount;
        this.leftArm.xRot = Mth.cos(swing) * 0.35F * limbSwingAmount;
        this.rightArm.zRot = 0.05F + Mth.sin(ageInTicks * 0.05F) * 0.03F;
        this.leftArm.zRot = -0.05F - Mth.sin(ageInTicks * 0.05F) * 0.03F;
    }
}
