package com.dunesrelics.client.model;

import com.dunesrelics.DunesRelics;
import com.dunesrelics.entity.Vulture;
import net.minecraft.client.model.HierarchicalModel;
import net.minecraft.client.model.geom.ModelLayerLocation;
import net.minecraft.client.model.geom.ModelPart;
import net.minecraft.client.model.geom.PartPose;
import net.minecraft.client.model.geom.builders.CubeListBuilder;
import net.minecraft.client.model.geom.builders.LayerDefinition;
import net.minecraft.client.model.geom.builders.MeshDefinition;
import net.minecraft.client.model.geom.builders.PartDefinition;
import net.minecraft.util.Mth;

/**
 * Vulture: a bald-headed scavenger with a pale ruff and a vast, fingered wingspan.
 * <p>Generated by tools/entity_models.py together with its texture; edit the script, not this file.
 */
@SuppressWarnings("unused")
public class VultureModel<T extends Vulture> extends HierarchicalModel<T> {
    public static final ModelLayerLocation LAYER_LOCATION = new ModelLayerLocation(DunesRelics.id("vulture"), "main");

    private final ModelPart root;
    private final ModelPart body;
    private final ModelPart ruff;
    private final ModelPart neck;
    private final ModelPart head;
    private final ModelPart beak;
    private final ModelPart tail;
    private final ModelPart leftWing;
    private final ModelPart leftWingTip;
    private final ModelPart rightWing;
    private final ModelPart rightWingTip;
    private final ModelPart leftLeg;
    private final ModelPart rightLeg;

    public VultureModel(ModelPart root) {
        this.root = root;
        this.body = root.getChild("body");
        this.ruff = this.body.getChild("ruff");
        this.neck = this.body.getChild("neck");
        this.head = this.neck.getChild("head");
        this.beak = this.head.getChild("beak");
        this.tail = this.body.getChild("tail");
        this.leftWing = this.body.getChild("left_wing");
        this.leftWingTip = this.leftWing.getChild("left_wing_tip");
        this.rightWing = this.body.getChild("right_wing");
        this.rightWingTip = this.rightWing.getChild("right_wing_tip");
        this.leftLeg = this.body.getChild("left_leg");
        this.rightLeg = this.body.getChild("right_leg");
    }

    public static LayerDefinition createBodyLayer() {
        MeshDefinition mesh = new MeshDefinition();
        PartDefinition root = mesh.getRoot();
        PartDefinition body = root.addOrReplaceChild("body", CubeListBuilder.create().texOffs(0, 0).addBox(-3.0F, -3.0F, -5.0F, 6.0F, 6.0F, 10.0F),
                PartPose.offsetAndRotation(0.0F, 15.0F, 0.0F, 0.0F, 0.0F, 0.0F));
        PartDefinition ruff = body.addOrReplaceChild("ruff", CubeListBuilder.create().texOffs(32, 8).addBox(-3.5F, -3.5F, -6.0F, 7.0F, 5.0F, 2.0F),
                PartPose.offsetAndRotation(0.0F, 0.0F, 0.0F, 0.0F, 0.0F, 0.0F));
        PartDefinition neck = body.addOrReplaceChild("neck", CubeListBuilder.create().texOffs(32, 0).addBox(-1.0F, -1.0F, -3.0F, 2.0F, 2.0F, 3.0F),
                PartPose.offsetAndRotation(0.0F, -1.5F, -5.0F, -0.4F, 0.0F, 0.0F));
        PartDefinition head = neck.addOrReplaceChild("head", CubeListBuilder.create().texOffs(42, 0).addBox(-1.5F, -2.0F, -3.0F, 3.0F, 3.0F, 3.0F),
                PartPose.offsetAndRotation(0.0F, 0.0F, -3.0F, 0.4F, 0.0F, 0.0F));
        PartDefinition beak = head.addOrReplaceChild("beak", CubeListBuilder.create().texOffs(54, 0).addBox(-0.5F, -1.5F, -5.0F, 1.0F, 2.0F, 2.0F),
                PartPose.offsetAndRotation(0.0F, 0.0F, 0.0F, 0.0F, 0.0F, 0.0F));
        PartDefinition tail = body.addOrReplaceChild("tail", CubeListBuilder.create().texOffs(38, 16).addBox(-2.5F, 0.0F, 0.0F, 5.0F, 1.0F, 6.0F),
                PartPose.offsetAndRotation(0.0F, -2.0F, 5.0F, -0.15F, 0.0F, 0.0F));
        PartDefinition leftWing = body.addOrReplaceChild("left_wing", CubeListBuilder.create().texOffs(0, 16).addBox(0.0F, -0.5F, 0.0F, 12.0F, 1.0F, 7.0F),
                PartPose.offsetAndRotation(3.0F, -2.5F, -3.0F, 0.0F, 0.0F, 0.0F));
        PartDefinition leftWingTip = leftWing.addOrReplaceChild("left_wing_tip", CubeListBuilder.create().texOffs(0, 24).addBox(0.0F, -0.5F, 0.0F, 9.0F, 1.0F, 6.0F),
                PartPose.offsetAndRotation(12.0F, 0.0F, 0.0F, 0.0F, 0.0F, 0.0F));
        PartDefinition rightWing = body.addOrReplaceChild("right_wing", CubeListBuilder.create().texOffs(0, 32).addBox(-12.0F, -0.5F, 0.0F, 12.0F, 1.0F, 7.0F),
                PartPose.offsetAndRotation(-3.0F, -2.5F, -3.0F, 0.0F, 0.0F, 0.0F));
        PartDefinition rightWingTip = rightWing.addOrReplaceChild("right_wing_tip", CubeListBuilder.create().texOffs(0, 40).addBox(-9.0F, -0.5F, 0.0F, 9.0F, 1.0F, 6.0F),
                PartPose.offsetAndRotation(-12.0F, 0.0F, 0.0F, 0.0F, 0.0F, 0.0F));
        PartDefinition leftLeg = body.addOrReplaceChild("left_leg", CubeListBuilder.create().texOffs(38, 24).addBox(-0.5F, 0.0F, -0.5F, 1.0F, 6.0F, 1.0F),
                PartPose.offsetAndRotation(1.5F, 3.0F, 1.0F, 0.0F, 0.0F, 0.0F));
        PartDefinition rightLeg = body.addOrReplaceChild("right_leg", CubeListBuilder.create().texOffs(38, 24).mirror().addBox(-0.5F, 0.0F, -0.5F, 1.0F, 6.0F, 1.0F).mirror(false),
                PartPose.offsetAndRotation(-1.5F, 3.0F, 1.0F, 0.0F, 0.0F, 0.0F));
        return LayerDefinition.create(mesh, 64, 64);
    }

    @Override
    public ModelPart root() {
        return this.root;
    }

    @Override
    public void setupAnim(T entity, float limbSwing, float limbSwingAmount, float ageInTicks, float netHeadYaw, float headPitch) {
        this.root().getAllParts().forEach(ModelPart::resetPose);
        this.head.yRot = netHeadYaw * Mth.DEG_TO_RAD * 0.6F;
        this.head.xRot += headPitch * Mth.DEG_TO_RAD * 0.5F;
        if (entity.onGround()) {
            // Wings folded along the back, standing on its legs.
            this.leftWing.yRot = -1.45F;
            this.rightWing.yRot = 1.45F;
            this.leftWingTip.yRot = 2.8F;
            this.rightWingTip.yRot = -2.8F;
            this.leftWing.zRot = 0.1F;
            this.rightWing.zRot = -0.1F;
            this.body.xRot = -0.35F;
            this.neck.xRot -= 0.2F;
            this.leftLeg.xRot = 0.35F;
            this.rightLeg.xRot = 0.35F;
            this.leftLeg.xRot += Mth.cos(limbSwing * 0.6662F) * 1.2F * limbSwingAmount;
            this.rightLeg.xRot += Mth.cos(limbSwing * 0.6662F + Mth.PI) * 1.2F * limbSwingAmount;
        } else {
            // Soaring: long glides broken by bouts of slow, heavy wingbeats.
            float bout = Math.max(0.0F, Mth.sin(ageInTicks * 0.035F + entity.getId()));
            float flap = Mth.sin(ageInTicks * 0.4F) * (0.1F + bout * 0.55F);
            this.leftWing.zRot = -0.12F - flap;
            this.rightWing.zRot = 0.12F + flap;
            this.leftWingTip.zRot = -0.08F - flap * 0.6F;
            this.rightWingTip.zRot = 0.08F + flap * 0.6F;
            this.leftLeg.xRot = 1.3F;
            this.rightLeg.xRot = 1.3F;
            this.tail.xRot += Mth.sin(ageInTicks * 0.05F) * 0.05F;
        }
    }
}
