"""Entity models for Dunes & Relics.

Each model is described once, here, and this script generates both the Java model class
(the LayerDefinition plus the animation code) and the matching entity texture, so the
UV layout of the texture always agrees with the boxes of the model.

Run from the repository root:  python3 tools/entity_models.py
"""
import math
import os
import random

from PIL import Image

from pixels import Palette, shade, mix, noise_pick

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
JAVA_DIR = os.path.join(ROOT, "src/main/java/com/dunesrelics/client/model")
TEX_DIR = os.path.join(ROOT, "src/main/resources/assets/dunesrelics/textures/entity")


class Cube:
    def __init__(self, u, v, x, y, z, w, h, d, painter, mirror=False, glow=None):
        self.glow = glow
        self.u, self.v = u, v
        self.x, self.y, self.z = x, y, z
        self.w, self.h, self.d = w, h, d
        self.painter = painter
        self.mirror = mirror

    def faces(self):
        u, v, w, h, d = self.u, self.v, self.w, self.h, self.d
        return {
            "top": (u + d, v, w, d),
            "bottom": (u + d + w, v, w, d),
            "right": (u, v + d, d, h),
            "front": (u + d, v + d, w, h),
            "left": (u + d + w, v + d, d, h),
            "back": (u + 2 * d + w, v + d, w, h),
        }


class Part:
    def __init__(self, name, parent, pivot, rot=(0, 0, 0), cubes=()):
        self.name, self.parent = name, parent
        self.pivot, self.rot = pivot, rot
        self.cubes = list(cubes)


def f(value):
    text = ("%.4f" % value).rstrip("0")
    if text.endswith("."):
        text += "0"
    return text + "F"


def camel(name):
    head, *rest = name.split("_")
    return head + "".join(p.capitalize() for p in rest)


def java_model(class_name, layer, parts, tex_w, tex_h, fields_doc, anim, extra_imports=(), translucent=False):
    lines = []
    for p in parts:
        builder = "CubeListBuilder.create()"
        for c in p.cubes:
            builder += ".texOffs(%d, %d)" % (c.u, c.v)
            if c.mirror:
                builder += ".mirror()"
            builder += ".addBox(%s, %s, %s, %s, %s, %s)" % tuple(f(n) for n in (c.x, c.y, c.z, c.w, c.h, c.d))
            if c.mirror:
                builder += ".mirror(false)"
        parent_var = "root" if p.parent is None else camel(p.parent)
        pose = "PartPose.offsetAndRotation(%s, %s, %s, %s, %s, %s)" % tuple(f(n) for n in (*p.pivot, *p.rot))
        lines.append("        PartDefinition %s = %s.addOrReplaceChild(\"%s\", %s,\n                %s);"
                     % (camel(p.name), parent_var, p.name, builder, pose))
    mesh = "\n".join(lines)
    fields = "\n".join("    private final ModelPart %s;" % camel(p.name) for p in parts)
    ctor = "\n".join("        this.%s = %s.getChild(\"%s\");"
                     % (camel(p.name), "root" if p.parent is None else "this." + camel(p.parent), p.name) for p in parts)
    imports = "\n".join(sorted(set(extra_imports)))
    return f"""package com.dunesrelics.client.model;

import com.dunesrelics.DunesRelics;
{imports}
import net.minecraft.client.model.HierarchicalModel;
import net.minecraft.client.model.geom.ModelLayerLocation;
import net.minecraft.client.model.geom.ModelPart;
import net.minecraft.client.model.geom.PartPose;
import net.minecraft.client.model.geom.builders.CubeListBuilder;
import net.minecraft.client.model.geom.builders.LayerDefinition;
import net.minecraft.client.model.geom.builders.MeshDefinition;
import net.minecraft.client.model.geom.builders.PartDefinition;
import net.minecraft.util.Mth;

/**
 * {fields_doc}
 * <p>Generated by tools/entity_models.py together with its texture; edit the script, not this file.
 */
@SuppressWarnings("unused")
public class {class_name}<T extends {layer[1].split(".")[-1]}> extends HierarchicalModel<T> {{
    public static final ModelLayerLocation LAYER_LOCATION = new ModelLayerLocation(DunesRelics.id("{layer[0]}"), "main");

    private final ModelPart root;
{fields}

    public {class_name}(ModelPart root) {{
        {"super(net.minecraft.client.renderer.RenderType::entityTranslucent);" if translucent else ""}
        this.root = root;
{ctor}
    }}

    public static LayerDefinition createBodyLayer() {{
        MeshDefinition mesh = new MeshDefinition();
        PartDefinition root = mesh.getRoot();
{mesh}
        return LayerDefinition.create(mesh, {tex_w}, {tex_h});
    }}

    @Override
    public ModelPart root() {{
        return this.root;
    }}

    @Override
    public void setupAnim(T entity, float limbSwing, float limbSwingAmount, float ageInTicks, float netHeadYaw, float headPitch) {{
        this.root().getAllParts().forEach(ModelPart::resetPose);
{anim}
    }}
}}
"""


def paint(parts, tex_w, tex_h, glow=False):
    img = Image.new("RGBA", (tex_w, tex_h), (0, 0, 0, 0))
    px = img.load()
    for p in parts:
        for c in p.cubes:
            painter = c.glow if glow else c.painter
            if painter is None:
                continue
            for face, (fx, fy, fw, fh) in c.faces().items():
                for j in range(int(fh)):
                    for i in range(int(fw)):
                        x, y = int(fx) + i, int(fy) + j
                        if 0 <= x < tex_w and 0 <= y < tex_h:
                            color = painter(face, i, j, int(fw), int(fh))
                            if color is not None:
                                px[x, y] = color if len(color) == 4 else (*color, 255)
    return img


# ----------------------------------------------------------------------------------------------- painters

def surface(pal, seed, shading=True, speckle=0.35, top_light=1.12, bottom_dark=0.8):
    rng = random.Random(seed)
    cache = {}

    def painter(face, i, j, w, h):
        key = (face, i, j, w, h)
        if key not in cache:
            base = noise_pick(pal, rng, speckle)
            if shading:
                if face == "top":
                    base = shade(base, top_light)
                elif face == "bottom":
                    base = shade(base, bottom_dark)
                elif face in ("left", "right"):
                    base = shade(base, 0.92)
            cache[key] = base
        return cache[key]

    return painter


def layered(*painters):
    """First painter returning a colour wins."""

    def painter(face, i, j, w, h):
        for p in painters:
            c = p(face, i, j, w, h)
            if c is not None:
                return c
        return None

    return painter


def on(face_names, fn):
    def painter(face, i, j, w, h):
        if face in face_names:
            return fn(i, j, w, h)
        return None

    return painter


# ----------------------------------------------------------------------------------------------- scorpion

def scorpion():
    tan = Palette("#b07a36", "#c28a42", "#cf9a4e", "#dcaa5c")
    dark = Palette("#6e4520", "#7e5228", "#8a5c2c")
    pale = Palette("#d9b27a", "#e3c18e")
    black = (38, 24, 14)
    sting = Palette("#3a2412", "#4a2e16", "#2c1a0c")

    def plates(i, j, w, h):
        # segmented armour plates along the length of the body (top face runs along z)
        if j % 3 == 0:
            return dark.c(1)
        return None

    body = layered(on(("top",), plates), on(("bottom",), lambda i, j, w, h: pale.c((i + j) % 2)),
                   surface(tan, 1))

    def face_front(i, j, w, h):
        if j == 0 and i in (1, w - 2):
            return black
        if j == 0 and i in (2, w - 3):
            return (70, 40, 20)
        if j == h - 1 and 2 <= i <= w - 3:
            return dark.c(0)
        return None

    head = layered(on(("front",), face_front), surface(tan, 2, top_light=1.05))
    arm = layered(surface(tan, 3))

    def claw_tip(i, j, w, h):
        if i in (0, w - 1) and j >= h - 2:
            return dark.c(0)
        return None

    claw = layered(on(("front",), lambda i, j, w, h: dark.c((i + j) % 3)),
                   on(("left", "right", "top", "bottom"), lambda i, j, w, h: dark.c(1) if i == 0 else None),
                   surface(tan, 4, top_light=1.15))

    def ring(i, j, w, h):
        return dark.c(0) if i == 0 else None

    tail = layered(on(("left", "right", "top", "bottom"), ring), surface(tan, 5))
    stinger = surface(sting, 6, speckle=0.2)
    leg = layered(on(("top", "front", "back", "bottom"), lambda i, j, w, h: dark.c(0) if i in (3, 6) else None),
                  surface(pale, 7))

    legs = []
    zs = [-3.5, -1.0, 1.5, 4.0]
    right_y = [-0.6, -0.2, 0.2, 0.6]
    names = ["front", "middle_front", "middle_hind", "hind"]
    for n, z, ry in zip(names, zs, right_y):
        legs.append(Part("right_%s_leg" % n, None, (-4, 19.5, z), (0, ry, -0.55),
                         [Cube(16, 32, -9, -1, -1, 9, 2, 2, leg)]))
        legs.append(Part("left_%s_leg" % n, None, (4, 19.5, z), (0, -ry, 0.55),
                         [Cube(16, 32, 0, -1, -1, 9, 2, 2, leg, mirror=True)]))

    parts = [
        Part("body", None, (0, 19, 0), cubes=[Cube(0, 0, -4, -2, -6, 8, 4, 12, body)]),
        Part("head", None, (0, 19.5, -6), cubes=[Cube(0, 16, -3, -1.5, -3, 6, 3, 3, head)]),
        Part("right_arm", None, (-2.5, 19.5, -8), (0, 0.5, 0), [Cube(20, 16, -1, -1, -5, 2, 2, 5, arm)]),
        Part("right_claw", "right_arm", (0, 0, -5), (0, 0, 0), [Cube(34, 16, -2, -1.5, -4, 4, 3, 4, claw)]),
        Part("left_arm", None, (2.5, 19.5, -8), (0, -0.5, 0), [Cube(20, 16, -1, -1, -5, 2, 2, 5, arm, mirror=True)]),
        Part("left_claw", "left_arm", (0, 0, -5), (0, 0, 0), [Cube(34, 16, -2, -1.5, -4, 4, 3, 4, claw, mirror=True)]),
        Part("tail1", None, (0, 18, 6), (0.9, 0, 0), [Cube(0, 24, -1.5, -1.5, 0, 3, 3, 5, tail)]),
        Part("tail2", "tail1", (0, 0, 5), (0.9, 0, 0), [Cube(16, 24, -1.5, -1.5, 0, 3, 3, 5, tail)]),
        Part("tail3", "tail2", (0, 0, 5), (0.8, 0, 0), [Cube(32, 24, -1, -1, 0, 2, 2, 5, tail)]),
        Part("tail4", "tail3", (0, 0, 5), (0.7, 0, 0), [Cube(46, 24, -1, -1, 0, 2, 2, 4, tail)]),
        Part("stinger", "tail4", (0, 0, 4), (0.6, 0, 0), [Cube(0, 32, -1, -1, 0, 2, 2, 2, stinger),
                                                          Cube(8, 32, -0.5, -0.5, 2, 1, 1, 2, stinger)]),
    ] + legs

    anim = """        this.head.yRot = netHeadYaw * Mth.DEG_TO_RAD * 0.5F;
        this.head.xRot = headPitch * Mth.DEG_TO_RAD * 0.3F;

        float walk = limbSwing * 0.6662F * 2.0F;
        float swingFront = -(Mth.cos(walk) * 0.4F) * limbSwingAmount;
        float swingMidFront = -(Mth.cos(walk + Mth.PI) * 0.4F) * limbSwingAmount;
        float swingMidHind = -(Mth.cos(walk + Mth.HALF_PI) * 0.4F) * limbSwingAmount;
        float swingHind = -(Mth.cos(walk + Mth.PI * 1.5F) * 0.4F) * limbSwingAmount;
        float liftFront = Math.abs(Mth.sin(limbSwing * 0.6662F) * 0.4F) * limbSwingAmount;
        float liftMidFront = Math.abs(Mth.sin(limbSwing * 0.6662F + Mth.PI) * 0.4F) * limbSwingAmount;
        float liftMidHind = Math.abs(Mth.sin(limbSwing * 0.6662F + Mth.HALF_PI) * 0.4F) * limbSwingAmount;
        float liftHind = Math.abs(Mth.sin(limbSwing * 0.6662F + Mth.PI * 1.5F) * 0.4F) * limbSwingAmount;
        this.rightFrontLeg.yRot += swingFront;
        this.leftFrontLeg.yRot -= swingFront;
        this.rightMiddleFrontLeg.yRot += swingMidFront;
        this.leftMiddleFrontLeg.yRot -= swingMidFront;
        this.rightMiddleHindLeg.yRot += swingMidHind;
        this.leftMiddleHindLeg.yRot -= swingMidHind;
        this.rightHindLeg.yRot += swingHind;
        this.leftHindLeg.yRot -= swingHind;
        this.rightFrontLeg.zRot -= liftFront;
        this.leftFrontLeg.zRot += liftFront;
        this.rightMiddleFrontLeg.zRot -= liftMidFront;
        this.leftMiddleFrontLeg.zRot += liftMidFront;
        this.rightMiddleHindLeg.zRot -= liftMidHind;
        this.leftMiddleHindLeg.zRot += liftMidHind;
        this.rightHindLeg.zRot -= liftHind;
        this.leftHindLeg.zRot += liftHind;

        // The tail sways slowly and the pincers flex; attacks lash the tail forward and snap the claws.
        float sway = Mth.sin(ageInTicks * 0.06F);
        this.tail1.yRot = sway * 0.12F;
        this.tail2.xRot += Mth.sin(ageInTicks * 0.09F) * 0.05F;
        this.tail4.xRot += Mth.sin(ageInTicks * 0.09F + 1.0F) * 0.06F;
        float strike = Mth.sin(this.attackTime * Mth.PI);
        this.tail1.xRot -= strike * 0.25F;
        this.tail3.xRot += strike * 0.35F;
        this.stinger.xRot += strike * 0.5F;
        float pinch = Mth.sin(ageInTicks * 0.15F) * 0.08F + strike * 0.45F;
        this.rightArm.yRot -= pinch;
        this.leftArm.yRot += pinch;
        this.rightClaw.yRot += Mth.sin(ageInTicks * 0.2F) * 0.1F;
        this.leftClaw.yRot -= Mth.sin(ageInTicks * 0.2F) * 0.1F;"""
    return "ScorpionModel", ("scorpion", "com.dunesrelics.entity.Scorpion"), parts, 64, 64, \
        "Scorpion: segmented body, two pincers, eight legs and a curled, striking tail.", anim


# ----------------------------------------------------------------------------------------------- scarab

def scarab():
    lapis = Palette("#1d3470", "#243f86", "#2c4b98", "#3a5fb0")
    sheen = Palette("#3f8fb6", "#4fa8c0")
    gold = Palette("#c9962c", "#e0b545", "#f2d06a")
    black = Palette("#141414", "#1e1c1a", "#2a2622")

    def shell(face, i, j, w, h):
        if face == "top":
            if i == w // 2 or i == w // 2 - 1 and w % 2 == 0:
                return gold.c(1) if j > 0 else gold.c(2)
            if i == 0 or i == w - 1:
                return gold.c(0)
            if (i + j) % 4 == 0 and j < h - 1:
                return sheen.c((i * 7 + j) % 2)
            return lapis.c((i * 3 + j * 5) % 4)
        if face in ("left", "right", "front", "back"):
            if j == 0:
                return gold.c(1)
            return lapis.c((i + j) % 2)
        return black.c((i + j) % 3)

    def head(face, i, j, w, h):
        if face == "front" and j == 0 and i in (0, w - 1):
            return (190, 40, 30)
        return gold.c((i + j) % 3) if face == "top" else black.c((i + j) % 3)

    horn = lambda face, i, j, w, h: gold.c((i + j) % 3)
    leg = lambda face, i, j, w, h: black.c((i + j) % 3)

    parts = [
        Part("body", None, (0, 21.5, 0), cubes=[Cube(0, 0, -2.5, -1.5, -3, 5, 3, 6, shell)]),
        Part("head", None, (0, 22, -3), cubes=[Cube(0, 9, -1.5, -1, -2, 3, 2, 2, head),
                                               Cube(10, 9, -1, -0.5, -3, 2, 1, 1, horn)]),
    ]
    for n, z, ry in (("front", -2, -0.5), ("middle", 0, 0.0), ("hind", 2, 0.5)):
        parts.append(Part("right_%s_leg" % n, None, (-2.5, 22.5, z), (0, ry, -0.5),
                          [Cube(16, 9, -3, -0.5, -0.5, 3, 1, 1, leg)]))
        parts.append(Part("left_%s_leg" % n, None, (2.5, 22.5, z), (0, -ry, 0.5),
                          [Cube(16, 9, 0, -0.5, -0.5, 3, 1, 1, leg, mirror=True)]))

    anim = """        this.head.yRot = netHeadYaw * Mth.DEG_TO_RAD * 0.4F;
        float walk = limbSwing * 1.4F;
        float a = Mth.cos(walk) * 0.6F * limbSwingAmount;
        float b = Mth.cos(walk + Mth.PI) * 0.6F * limbSwingAmount;
        this.rightFrontLeg.yRot += a;
        this.leftMiddleLeg.yRot -= a;
        this.rightHindLeg.yRot += a;
        this.leftFrontLeg.yRot -= b;
        this.rightMiddleLeg.yRot += b;
        this.leftHindLeg.yRot -= b;
        this.body.zRot = Mth.sin(walk) * 0.05F * limbSwingAmount;"""
    return "ScarabModel", ("scarab", "com.dunesrelics.entity.Scarab"), parts, 32, 16, \
        "Scarab: a lapis-blue beetle with a gilded shell seam and six scurrying legs.", anim


# ----------------------------------------------------------------------------------------------- meerkat

def meerkat():
    fur = Palette("#b88f5c", "#c49b66", "#cfa872", "#d8b47e")
    back = Palette("#8a6a44", "#9a7650")
    belly = Palette("#e3cc9f", "#ead6ad")
    dark = (48, 34, 26)
    nose = (30, 22, 18)

    def torso(face, i, j, w, h):
        if face == "top":
            # faint bands across the back
            if j % 3 == 1:
                return back.c(i % 2)
            return fur.c((i * 5 + j * 3) % 4)
        if face == "bottom":
            return belly.c((i + j) % 2)
        if face in ("left", "right") and j >= h - 1:
            return belly.c(0)
        return fur.c((i * 3 + j * 7) % 4)

    def head(face, i, j, w, h):
        if face == "front":
            if j == 1 and i in (0, w - 1):
                return dark
            if j in (1, 2) and i in (0, 1, w - 2, w - 1):
                return (32, 24, 20) if j == 1 and i in (1, w - 2) else dark
            if j == h - 1:
                return belly.c(0)
        if face == "top":
            return fur.c((i + j) % 3)
        if face == "bottom":
            return belly.c(1)
        return fur.c((i * 3 + j) % 4)

    def snout(face, i, j, w, h):
        if face == "front" and j == 0:
            return nose
        return belly.c((i + j) % 2) if face != "top" else fur.c(2)

    ear = lambda face, i, j, w, h: dark
    leg = lambda face, i, j, w, h: fur.c((i + j) % 3) if j < h - 1 else dark

    def tail(face, i, j, w, h):
        if face in ("back",):
            return dark
        if face in ("top", "bottom", "left", "right"):
            # the last pixels along the tail are dark
            along = j if face in ("top", "bottom") else i
            span = h if face in ("top", "bottom") else w
            if along >= span - 2:
                return dark
        return fur.c((i + j) % 4)

    parts = [
        Part("body", None, (0, 19, 2), cubes=[Cube(0, 0, -2, -2.5, -8, 4, 4, 8, torso)]),
        Part("head", "body", (0, -1.5, -8), cubes=[Cube(24, 0, -2, -2.5, -3, 4, 4, 3, head),
                                                   Cube(38, 0, -1, -0.5, -5, 2, 2, 2, snout)]),
        Part("right_ear", "head", (-2, -2, -1), cubes=[Cube(46, 0, -0.5, -0.5, -0.5, 1, 1, 1, ear)]),
        Part("left_ear", "head", (2, -2, -1), cubes=[Cube(46, 0, -0.5, -0.5, -0.5, 1, 1, 1, ear, mirror=True)]),
        Part("right_front_leg", "body", (-1.2, 1, -6.5), cubes=[Cube(0, 12, -1, 0, -1, 2, 4, 2, leg)]),
        Part("left_front_leg", "body", (1.2, 1, -6.5), cubes=[Cube(0, 12, -1, 0, -1, 2, 4, 2, leg, mirror=True)]),
        Part("tail", "body", (0, -1, 0), (-0.3, 0, 0), [Cube(8, 12, -0.5, -0.5, 0, 1, 1, 8, tail)]),
        Part("right_hind_leg", None, (-1.5, 20, 1), cubes=[Cube(0, 18, -1, 0, -1, 2, 4, 2, leg)]),
        Part("left_hind_leg", None, (1.5, 20, 1), cubes=[Cube(0, 18, -1, 0, -1, 2, 4, 2, leg, mirror=True)]),
    ]

    anim = """        float partialTick = ageInTicks - entity.tickCount;
        float stand = entity.getStandAnim(partialTick);

        // Walking.
        float walk = limbSwing * 0.6662F * 1.4F;
        float swing = Mth.cos(walk) * 1.2F * limbSwingAmount * (1.0F - stand);
        this.rightFrontLeg.xRot = swing;
        this.leftFrontLeg.xRot = -swing;
        this.rightHindLeg.xRot = -swing;
        this.leftHindLeg.xRot = swing;
        this.tail.xRot += Mth.cos(walk) * 0.15F * limbSwingAmount;
        this.tail.yRot = Mth.sin(ageInTicks * 0.08F) * 0.12F * (1.0F - stand);

        // Lookout pose: rear up on the hind legs, the tail propping the body up behind.
        this.body.xRot = -1.35F * stand;
        this.head.xRot = headPitch * Mth.DEG_TO_RAD + 1.35F * stand;
        this.head.yRot = netHeadYaw * Mth.DEG_TO_RAD;
        this.rightFrontLeg.xRot += 1.1F * stand;
        this.leftFrontLeg.xRot += 1.1F * stand;
        this.tail.xRot += 0.9F * stand;

        // Dancing to a jukebox: sway and bob the head.
        if (entity.isDancing()) {
            this.body.zRot = Mth.sin(ageInTicks * 0.4F) * 0.15F;
            this.head.zRot = Mth.sin(ageInTicks * 0.8F) * 0.3F;
            this.rightFrontLeg.zRot = Mth.sin(ageInTicks * 0.8F) * 0.5F;
            this.leftFrontLeg.zRot = -Mth.sin(ageInTicks * 0.8F) * 0.5F;
        }"""
    return "MeerkatModel", ("meerkat", "com.dunesrelics.entity.Meerkat"), parts, 64, 32, \
        "Meerkat: a slender, striped desert mongoose that rears up to keep a lookout.", anim


# ----------------------------------------------------------------------------------------------- vulture

def vulture():
    plumage = Palette("#2a221e", "#332a24", "#3d322b", "#463a31")
    edge = Palette("#5a4a3e", "#6a584a")
    ruff = Palette("#cfc8bc", "#ddd6ca", "#e8e2d8")
    skin = Palette("#d9a198", "#e0aba2", "#c98a82")
    beak = Palette("#e3d6b4", "#d4c49c")
    tip = (40, 36, 34)
    legc = Palette("#8f8578", "#9e9486")

    def body(face, i, j, w, h):
        if face == "top" and j % 3 == 2:
            return edge.c(i % 2)
        if face == "bottom":
            return plumage.c((i + j) % 2 + 2)
        return plumage.c((i * 3 + j * 5) % 4)

    neck = lambda face, i, j, w, h: skin.c((i + j * 2) % 3)

    def head(face, i, j, w, h):
        if face in ("left", "right") and j == 1 and i == 1:
            return (30, 20, 20)
        return skin.c((i * 2 + j) % 3)

    def beak_p(face, i, j, w, h):
        if face == "front" or (face in ("left", "right", "top", "bottom") and i == 0 and face in ("top", "bottom")):
            return tip
        if face in ("left", "right") and i == 0:
            return tip
        return beak.c((i + j) % 2)

    ruff_p = lambda face, i, j, w, h: ruff.c((i * 7 + j * 3) % 3)

    def wing(tip_part):
        def painter(face, i, j, w, h):
            if face in ("top", "bottom"):
                # j runs from the leading edge (0) to the trailing edge (h-1): flight feathers,
                # with ragged "fingers" at the trailing edge of the tip.
                if tip_part and j >= h - 2 and i % 2 == 1:
                    return None
                if j >= h - 3:
                    return edge.c(i % 2) if i % 2 == 0 else plumage.c(1)
                if j == 0:
                    return plumage.c(0)
                return plumage.c((i + j * 3) % 4)
            return plumage.c(0)
        return painter

    tail = lambda face, i, j, w, h: None if face in ("top", "bottom") and j == h - 1 and i % 2 else plumage.c((i + j) % 4)
    leg = lambda face, i, j, w, h: legc.c((i + j) % 2) if j < h - 1 else tip

    parts = [
        Part("body", None, (0, 15, 0), cubes=[Cube(0, 0, -3, -3, -5, 6, 6, 10, body)]),
        Part("ruff", "body", (0, 0, 0), cubes=[Cube(32, 8, -3.5, -3.5, -6, 7, 5, 2, ruff_p)]),
        Part("neck", "body", (0, -1.5, -5), (-0.4, 0, 0), [Cube(32, 0, -1, -1, -3, 2, 2, 3, neck)]),
        Part("head", "neck", (0, 0, -3), (0.4, 0, 0), [Cube(42, 0, -1.5, -2, -3, 3, 3, 3, head)]),
        Part("beak", "head", (0, 0, 0), cubes=[Cube(54, 0, -0.5, -1.5, -5, 1, 2, 2, beak_p)]),
        Part("tail", "body", (0, -2, 5), (-0.15, 0, 0), [Cube(38, 16, -2.5, 0, 0, 5, 1, 6, tail)]),
        Part("left_wing", "body", (3, -2.5, -3), cubes=[Cube(0, 16, 0, -0.5, 0, 12, 1, 7, wing(False))]),
        Part("left_wing_tip", "left_wing", (12, 0, 0), cubes=[Cube(0, 24, 0, -0.5, 0, 9, 1, 6, wing(True))]),
        Part("right_wing", "body", (-3, -2.5, -3), cubes=[Cube(0, 32, -12, -0.5, 0, 12, 1, 7, wing(False))]),
        Part("right_wing_tip", "right_wing", (-12, 0, 0), cubes=[Cube(0, 40, -9, -0.5, 0, 9, 1, 6, wing(True))]),
        Part("left_leg", "body", (1.5, 3, 1), cubes=[Cube(38, 24, -0.5, 0, -0.5, 1, 6, 1, leg)]),
        Part("right_leg", "body", (-1.5, 3, 1), cubes=[Cube(38, 24, -0.5, 0, -0.5, 1, 6, 1, leg, mirror=True)]),
    ]

    anim = """        this.head.yRot = netHeadYaw * Mth.DEG_TO_RAD * 0.6F;
        this.head.xRot += headPitch * Mth.DEG_TO_RAD * 0.5F;
        if (entity.onGround()) {
            // Wings folded along the back, standing on its legs.
            this.leftWing.yRot = -1.45F;
            this.rightWing.yRot = 1.45F;
            this.leftWingTip.yRot = 2.8F;
            this.rightWingTip.yRot = -2.8F;
            this.leftWing.zRot = 0.1F;
            this.rightWing.zRot = -0.1F;
            this.body.xRot = -0.35F;
            this.neck.xRot -= 0.2F;
            this.leftLeg.xRot = 0.35F;
            this.rightLeg.xRot = 0.35F;
            this.leftLeg.xRot += Mth.cos(limbSwing * 0.6662F) * 1.2F * limbSwingAmount;
            this.rightLeg.xRot += Mth.cos(limbSwing * 0.6662F + Mth.PI) * 1.2F * limbSwingAmount;
        } else {
            // Soaring: long glides broken by bouts of slow, heavy wingbeats.
            float bout = Math.max(0.0F, Mth.sin(ageInTicks * 0.035F + entity.getId()));
            float flap = Mth.sin(ageInTicks * 0.4F) * (0.1F + bout * 0.55F);
            this.leftWing.zRot = -0.12F - flap;
            this.rightWing.zRot = 0.12F + flap;
            this.leftWingTip.zRot = -0.08F - flap * 0.6F;
            this.rightWingTip.zRot = 0.08F + flap * 0.6F;
            this.leftLeg.xRot = 1.3F;
            this.rightLeg.xRot = 1.3F;
            this.tail.xRot += Mth.sin(ageInTicks * 0.05F) * 0.05F;
        }"""
    return "VultureModel", ("vulture", "com.dunesrelics.entity.Vulture"), parts, 64, 64, \
        "Vulture: a bald-headed scavenger with a pale ruff and a vast, fingered wingspan.", anim


def main():
    os.makedirs(JAVA_DIR, exist_ok=True)
    os.makedirs(TEX_DIR, exist_ok=True)
    import volcanic_models
    for build in (scorpion, scarab, meerkat, vulture) + volcanic_models.MODELS:
        result = build()
        class_name, layer, parts, tw, th, doc, anim = result[:7]
        translucent = len(result) > 7 and result[7]
        with open(os.path.join(JAVA_DIR, class_name + ".java"), "w") as out:
            out.write(java_model(class_name, layer, parts, tw, th, doc, anim, ["import " + layer[1] + ";"], translucent))
        paint(parts, tw, th).save(os.path.join(TEX_DIR, layer[0] + ".png"))
        if any(c.glow for p in parts for c in p.cubes):
            paint(parts, tw, th, glow=True).save(os.path.join(TEX_DIR, layer[0] + "_glow.png"))
        print("generated", class_name)
    import world_models
    world_models.main()


if __name__ == "__main__":
    main()
